### ISSUE TITLE
Mongooseplus licensing issues

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan#102]
you disabled web server support in c5bf9ab0677e96, albeit only for linux.  The license violation the commit addresses is platform-agnostic and you cannot ship binaries with web server support at all at the moment.  web server support should be disabled across the bank for now, I guess.

**Comment by ereOn** [comment]
@leggewie That makes sense indeed.

I'll remove the code altogether. This feature doesn't fit with the new philosophy I intend to apply for the next major versions anyway.

**Comment by s-vincent** [comment]
For the moment, we can add a #define like USE_MONGOOSE in the SConscript.

So all in all, compilation will be platform agnostic without mongoose by default waiting for replacement.

@ereon WDYT ?

**Comment by s-vincent** [comment]
PR #139 to review.

**Comment by ereOn** [comment]
That works for me.

**Comment by leggewie** [comment]
Great!

Just make sure the binaries built by the official project are built without mongoose for all platforms.
