### ISSUE TITLE
Webserver does not send certificate

### ISSUE THREAD

**Issue by xp-1000** [freelan-developers/freelan#108]
Hi all,
I recently discovered freelan, it is a wonderfull tool. Very good job.
I currently try to replace my centralized vpn (openvpn) by hybrid vpn with freelan.
Almost all features I have with openvpn works on freelan except 2 things : 
- Provide dynamic ip via internal dhcp (not the subject here)
- Provide certificates to clients from webserver
# Situation

I works on windows 7 64 bit with this binary : https://github.com/freelan-developers/freelan/releases/download/2.0/freelan-2.0.0-amd64-install.exe
I run 2 nodes, one which will be the server providing certificate and another which be the client getting the certificate.
I tried with serveral configurations in freelan.cfg and in network (remote, local network, localhost).
Finally, I simplified the test to the maximum with keeping the original freelan.cfg and use commands based on scripts start-client and start-server located in scripts freelan folder.
# Configurations
## Node 1 (server)

freelan.cfg is the original file, and my command is :
`freelan.exe -d --server.enabled=yes --server.authentication_script=auth.bat`
auth.bat is a stupid batch script which always return 0 (for tests only)
## Node 2 (client)

freelan.cfg is the original file, and my command is :
`freelan -d --client.enabled=yes --client.disable_peer_verification=yes --client.disable_host_verification=yes --fscp.listen_on=0.0.0.0:12001 --client.username="user" --client.password="ok" --client.public_endpoint=0.0.0.0 --client.public_endpoint=:: --client.public_endpoint=localhost:12001`
# Problem

Client connect to webserver, server node can authenticed the client but the client does not get response from the server when it ask for a certificate.
## Node 1 (server) logs before quitting client :

> 2016-04-26T07:10:51.456153 [INFORMATION] Reading configuration file at: "C:\Prog
> ram Files\FreeLAN/config/freelan.cfg"
> 2016-04-26T07:10:51.468154 [DEBUG] Opening core...
> 2016-04-26T07:10:51.473154 [WARNING] No user certificate/private key or pre-shared key set. Generating a temporary certificate/private key pair...
> 2016-04-26T07:10:51.854176 [WARNING] Using a generated temporary certificate (CN=X-QUENTIN) prevents reliable authentication ! Generate and specify a static certificate/key pair for use in production.
> 2016-04-26T07:10:51.870177 [INFORMATION] Starting FSCP server...
> 2016-04-26T07:10:51.876177 [IMPORTANT] Core set to listen on: 0.0.0.0:12000
> 2016-04-26T07:10:51.882178 [INFORMATION] Building CA store...
> 2016-04-26T07:10:51.887178 [INFORMATION] FSCP server started.
> 2016-04-26T07:10:51.919180 [IMPORTANT] Tap adapter "Connexion au rÚseau local 2" opened in mode tap with a MTU set to: 1446
> 2016-04-26T07:10:51.930180 [IMPORTANT] MSS override enabled with a value of: 1392
> 2016-04-26T07:10:51.937181 [INFORMATION] IPv4 address: 9.0.0.1/24
> 2016-04-26T07:10:51.943181 [INFORMATION] IPv6 address: 2aa1::1/8
> 2016-04-26T07:10:53.824289 [INFORMATION] Setting interface metric to: 3
> 2016-04-26T07:10:53.830289 [INFORMATION] Putting interface into the connected state.
> 2016-04-26T07:10:53.840290 [INFORMATION] The DHCP proxy is enabled.
> 2016-04-26T07:10:53.852290 [INFORMATION] Not advertising any routes.
> 2016-04-26T07:10:53.859291 [INFORMATION] Not advertising any DNS servers.
> 2016-04-26T07:10:53.866291 [WARNING] No private key set for the web server. Generating a temporary one...
> 2016-04-26T07:10:53.866291 [INFORMATION] Starting tap adapter's thread...
> 2016-04-26T07:10:54.227312 [WARNING] No certificate set for the web server. Generating a temporary one...
> 2016-04-26T07:10:54.251313 [WARNING] Using a dynamically generated certificate/private key for the web server will force web clients to disable peer verification. Is this what you really want ?
> 2016-04-26T07:10:54.267314 [WARNING] No private key set for the web server's CA. Generating a temporary one...
> 2016-04-26T07:10:54.675337 [WARNING] No certificate set for the web server's CA. Generating a temporary one...
> 2016-04-26T07:10:54.700339 [WARNING] Using a dynamically generated certificate/private key for the web server's CA will cause the session lifecycle to be tied to the one of the server.
> 2016-04-26T07:10:54.718340 [DEBUG] Web server's listen endpoint set to 0.0.0.0:443.
> 2016-04-26T07:10:54.726340 [INFORMATION] Starting https web server on 0.0.0.0:443...
> 2016-04-26T07:10:54.734341 [INFORMATION] Web server started.
> 2016-04-26T07:10:54.739341 [DEBUG] Core opened.
> 2016-04-26T07:10:54.743341 [INFORMATION] Using 6 thread(s).
> 2016-04-26T07:10:54.747341 [IMPORTANT] Execution started.
> 2016-04-26T07:10:54.752342 [DEBUG] Thread #0 started.
> 2016-04-26T07:10:54.752342 [DEBUG] Thread #1 started.
> 2016-04-26T07:10:54.752342 [DEBUG] Thread #2 started.
> 2016-04-26T07:10:54.752342 [DEBUG] Thread #3 started.
> 2016-04-26T07:10:54.752342 [DEBUG] Thread #4 started.
> 2016-04-26T07:10:54.753342 [DEBUG] Thread #5 started.
> 2016-04-26T07:11:14.286459 [INFORMATION] Web server - Received GET request from 127.0.0.1:58167 for /request_ca_certificate/ (0 byte(s) content).
> 2016-04-26T07:11:14.301460 [DEBUG] --- Headers follow ---
> 2016-04-26T07:11:14.306460 [DEBUG] authorization: Basic a2l3aXM6b2s=
> 2016-04-26T07:11:14.313461 [DEBUG] host: 127.0.0.1
> 2016-04-26T07:11:14.318461 [DEBUG] accept: _/_
> 2016-04-26T07:11:14.323461 [DEBUG] --- End of headers ---
> 2016-04-26T07:11:14.328461 [DEBUG] Calling script C:\Program Files\FreeLAN\bin\auth.bat...
> 2016-04-26T07:11:14.406466 [DEBUG] Script C:\Program Files\FreeLAN\bin\auth.bat returned 0.
> 2016-04-26T07:11:14.414466 [DEBUG] Authentication succeeded for user "user".
> 2016-04-26T07:11:14.421467 [DEBUG] user (127.0.0.1:58167) requested the CA certificate.
> 2016-04-26T07:11:14.429467 [INFORMATION] Web server - Received POST request from 127.0.0.1:58168 for /request_certificate/ (603 byte(s) content).
> 2016-04-26T07:11:14.441468 [DEBUG] --- Headers follow ---
> 2016-04-26T07:11:14.446468 [DEBUG] authorization: Basic a2l3aXM6b2s=
> 2016-04-26T07:11:14.452468 [DEBUG] host: 127.0.0.1
> 2016-04-26T07:11:14.457469 [DEBUG] accept: _/_
> 2016-04-26T07:11:14.461469 [DEBUG] content-type: application/octet-stream
> 2016-04-26T07:11:14.467469 [DEBUG] content-length: 603
> 2016-04-26T07:11:14.472470 [DEBUG] --- End of headers ---
> 2016-04-26T07:11:14.477470 [DEBUG] Calling script C:\Program Files\FreeLAN\bin\auth.bat...
> 2016-04-26T07:11:14.497471 [DEBUG] Script C:\Program Files\FreeLAN\bin\auth.bat returned 0.
> 2016-04-26T07:11:14.505472 [DEBUG] Authentication succeeded for user "user".
> ## Node 2 (client) logs :
> 
> 2016-04-26T07:11:12.775373 [INFORMATION] Reading configuration file at: "C:\Program Files\FreeLAN/config/freelan.cfg"
> 2016-04-26T07:11:12.784373 [DEBUG] Opening core...
> 2016-04-26T07:11:12.787373 [INFORMATION] Starting web client to contact web server at https://127.0.0.1:443...
> 2016-04-26T07:11:12.794374 [WARNING] Web client configured to ignore peer verification: you are vulnerable to man-in-the-middle attacks !
> 2016-04-26T07:11:12.802374 [WARNING] Web client configured to ignore host verification: you are vulnerable to man-in-the-middle attacks !
> 2016-04-26T07:11:12.809375 [INFORMATION] Web client started.
> 2016-04-26T07:11:12.813375 [INFORMATION] No user or private key set. Requesting one from web server...
> 2016-04-26T07:11:12.819375 [INFORMATION] Requesting a client certificate from the web server...
> 2016-04-26T07:11:13.839433 [INFORMATION] Requesting the CA certificate from the web server...
> 2016-04-26T07:11:13.850434 [IMPORTANT] Tap adapter "Connexion au rÚseau local 3" opened in mode tap with a MTU set to: 1446
> 2016-04-26T07:11:13.857434 [IMPORTANT] MSS override enabled with a value of: 1392
> 2016-04-26T07:11:13.862435 [INFORMATION] IPv4 address: 9.0.0.1/24
> 2016-04-26T07:11:13.866435 [INFORMATION] IPv6 address: 2aa1::1/8
> 2016-04-26T07:11:14.110449 [INFORMATION] Setting interface metric to: 3
> 2016-04-26T07:11:14.114449 [INFORMATION] Putting interface into the connected state.
> 2016-04-26T07:11:14.121450 [INFORMATION] The DHCP proxy is enabled.
> 2016-04-26T07:11:14.147451 [INFORMATION] Not advertising any routes.
> 2016-04-26T07:11:14.152451 [INFORMATION] Not advertising any DNS servers.
> 2016-04-26T07:11:14.157452 [DEBUG] Core opened.
> 2016-04-26T07:11:14.160452 [INFORMATION] Using 6 thread(s).
> 2016-04-26T07:11:14.157452 [INFORMATION] Starting tap adapter's thread...
> 2016-04-26T07:11:14.164452 [IMPORTANT] Execution started.
> 2016-04-26T07:11:14.174453 [DEBUG] Thread #0 started.
> 2016-04-26T07:11:14.174453 [DEBUG] Thread #1 started.
> 2016-04-26T07:11:14.174453 [DEBUG] Thread #2 started.
> 2016-04-26T07:11:14.174453 [DEBUG] Thread #3 started.
> 2016-04-26T07:11:14.174453 [DEBUG] Thread #4 started.
> 2016-04-26T07:11:14.174453 [DEBUG] Thread #5 started.
> 2016-04-26T07:11:14.286459 [ERROR] Error while sending HTTP(S) request to https://127.0.0.1:443/request_ca_certificate/: Server returned nothing (no headers, no data) (curl::error:52)
> 2016-04-26T07:11:14.287459 [ERROR] Error while sending HTTP(S) request to https://127.0.0.1:443/request_certificate/: Server returned nothing (no headers, no data) (curl::error:52)
> 2016-04-26T07:11:14.302460 [ERROR] The CA certificate request to the web server failed: Server returned nothing (no headers, no data) (curl::error:52). Retrying in 00:00:05...
> 2016-04-26T07:11:14.316461 [ERROR] The certificate request to the web server failed: Server returned nothing (no headers, no data) (curl::error:52). Retrying in 00:00:05...
> 2016-04-26T07:11:19.331748 [INFORMATION] Requesting the CA certificate from the web server...
> 2016-04-26T07:11:19.343748 [INFORMATION] Requesting a client certificate from the web server...
> 2016-04-26T07:11:19.362749 [ERROR] Error while sending HTTP(S) request to https://127.0.0.1:443/request_ca_certificate/: Server returned nothing (no headers, no data) (curl::error:52)
> 2016-04-26T07:11:19.383751 [ERROR] The CA certificate request to the web server failed: Server returned nothing (no headers, no data) (curl::error:52). Retrying in 00:00:07.506000...
> 2016-04-26T07:11:19.751772 [ERROR] Error while sending HTTP(S) request to https://127.0.0.1:443/request_certificate/: Server returned nothing (no headers, no data) (curl::error:52)
> 2016-04-26T07:11:19.768773 [ERROR] The certificate request to the web server failed: Server returned nothing (no headers, no data) (curl::error:52). Retrying in 00:00:07.506000...
> 2016-04-26T07:11:21.336862 [WARNING] Signal caught (2): exiting...
> 2016-04-26T07:11:21.340862 [DEBUG] Closing core...
> 2016-04-26T07:11:21.343863 [INFORMATION] Tap adapter's thread is now stopped.
> 2016-04-26T07:11:21.376865 [INFORMATION] Closing web client...
> 2016-04-26T07:11:21.381865 [INFORMATION] Unregistering from the web server...
> 2016-04-26T07:11:21.392865 [INFORMATION] Web client closed.
> 2016-04-26T07:11:21.396866 [DEBUG] Core closed.
> 2016-04-26T07:11:21.421867 [ERROR] Error while sending HTTP(S) request to https://127.0.0.1:443/unregister/: Server returned nothing (no headers, no data) (curl::error:52)
> 2016-04-26T07:11:21.436868 [ERROR] The unregistration from the web server failed: Server returned nothing (no headers, no data) (curl::error:52). Not retrying to avoid delaying shutdown.
> 2016-04-26T07:11:21.456869 [DEBUG] Thread #0 stopped.
> 2016-04-26T07:11:21.456869 [DEBUG] Thread #3 stopped.
> 2016-04-26T07:11:21.456869 [DEBUG] Thread #5 stopped.
> 2016-04-26T07:11:21.456869 [DEBUG] Thread #1 stopped.
> 2016-04-26T07:11:21.456869 [DEBUG] Thread #4 stopped.
> 2016-04-26T07:11:21.456869 [DEBUG] Thread #2 stopped.
> 2016-04-26T07:11:21.485871 [IMPORTANT] Execution stopped.
## Node 1 (server) logs after quitting client :

> 2016-04-26T07:11:21.507872 [WARNING] user (127.0.0.1:58173) asked to be unregistered but is not currently registered. Doing nothing.
> 2016-04-26T07:13:51.468449 [DEBUG] Sending routes request to all hosts.
> 2016-04-26T07:16:51.471745 [DEBUG] Sending routes request to all hosts.
> 2016-04-26T07:19:51.476041 [DEBUG] Sending routes request to all hosts.
> 2016-04-26T07:22:51.480336 [DEBUG] Sending routes request to all hosts.
> 2016-04-26T07:25:51.483632 [DEBUG] Sending routes request to all hosts.
> 2016-04-26T07:25:54.910828 [WARNING] Signal caught (2): exiting...
> 2016-04-26T07:25:54.916828 [DEBUG] Closing core...
> 2016-04-26T07:25:54.920828 [INFORMATION] Closing web server...
> 2016-04-26T07:25:55.570866 [INFORMATION] Web server closed.
> 2016-04-26T07:25:55.575866 [INFORMATION] Tap adapter's thread is now stopped.
> 2016-04-26T07:25:55.586866 [INFORMATION] Closing FSCP server...
> 2016-04-26T07:25:55.592867 [INFORMATION] FSCP server closed.
> 2016-04-26T07:25:55.599867 [DEBUG] Core closed.
> 2016-04-26T07:25:55.605868 [DEBUG] Thread #5 stopped.
> 2016-04-26T07:25:55.605868 [DEBUG] Thread #4 stopped.
> 2016-04-26T07:25:55.605868 [DEBUG] Thread #3 stopped.
> 2016-04-26T07:25:55.605868 [DEBUG] Thread #2 stopped.
> 2016-04-26T07:25:55.605868 [DEBUG] Thread #0 stopped.
> 2016-04-26T07:25:55.605868 [DEBUG] Thread #1 stopped.
> 2016-04-26T07:25:55.652870 [IMPORTANT] Execution stopped.
# Manual tests

I tested with pure curl and firefox the different url to the webserver and I confirm that it returns a 200 OK status but no header or data.
I would add some debug print to program and try to debug it : https://github.com/freelan-developers/freelan/blob/43062cd97e869df3334c72abf0f99797ff20e539/libs/freelan/src/server.cpp#L186
Unfortunaly, I can compile freelan on linux but I notice that the webserver was not available and I cannot compile freelan on windows (tried with visual studio 2013 but after lot of errors resolved I dropped ..)
# Conclusion

This error seems different of #84 
May be I have a wrong configuration or I missed something but I read the config file already several times and I have no more ideas. 
So I hope you could help me with this.
I could not replace my openvpn with freelan without this feature but whatever happens I will make a donation because it is a very interesting application which has been realy well designed.

Bye

**Comment by s-vincent** [comment]
Related to #84.
