### ISSUE TITLE
CentOS 7.2 - got a error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown

### ISSUE THREAD

**Issue by strobe** [freelan-developers/freelan#109]
I've compiled master branch (43062cd97e869df3334c72abf0f99797ff20e539) and got this error on 2 CentoS 7 hosts:

```
2016-05-15T07:52:16.182495 [DEBUG] Received SESSION_REQUEST from 192.168.33.11:12000 (default: accept│
).                                                                                                   │
2016-05-15T07:52:16.182509 [DEBUG] Cipher suites capabilities: ecdhe_rsa_aes256_gcm_sha384 ecdhe_rsa_│
aes128_gcm_sha256                                                                                    │
2016-05-15T07:52:16.182517 [DEBUG] Elliptic curve capabilities: sect571k1 secp384r1                  │
2016-05-15T07:52:16.183354 [TRACE] Received a SESSION_REQUEST from 192.168.33.11:12000 with session n│
umber 0 and cipher suite ecdhe_rsa_aes256_gcm_sha384_sect571k1. No current session exist: preparing o│
ne and sending it.                                                                                   │
2016-05-15T07:52:16.191573 [ERROR] Fatal exception occured in thread #0: error:100AE081:elliptic curv│
e routines:EC_GROUP_new_by_curve_name:unknown group                                                  │
2016-05-15T07:52:16.191601 [DEBUG] Closing core...                                                   │
2016-05-15T07:52:16.191659 [INFORMATION] Tap adapter's thread is now stopped.                        │
2016-05-15T07:52:16.197105 [INFORMATION] Closing FSCP server...                                      │
2016-05-15T07:52:16.199434 [INFORMATION] FSCP server closed.
```

```
CentOS Linux release 7.2.1511 (Core)
```

```
> openssl ciphers
ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-DSS-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:DHE-DSS-CAMELLIA256-SHA:ECDH-RSA-AES256-GCM-SHA384:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-RSA-AES256-SHA384:ECDH-ECDSA-AES256-SHA384:ECDH-RSA-AES256-SHA:ECDH-ECDSA-AES256-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA:PSK-AES256-CBC-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-DSS-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:DHE-RSA-SEED-SHA:DHE-DSS-SEED-SHA:DHE-RSA-CAMELLIA128-SHA:DHE-DSS-CAMELLIA128-SHA:EDH-RSA-DES-CBC3-SHA:EDH-DSS-DES-CBC3-SHA:ECDH-RSA-AES128-GCM-SHA256:ECDH-ECDSA-AES128-GCM-SHA256:ECDH-RSA-AES128-SHA256:ECDH-ECDSA-AES128-SHA256:ECDH-RSA-AES128-SHA:ECDH-ECDSA-AES128-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:SEED-SHA:CAMELLIA128-SHA:DES-CBC3-SHA:IDEA-CBC-SHA:PSK-AES128-CBC-SHA:PSK-3DES-EDE-CBC-SHA:KRB5-IDEA-CBC-SHA:KRB5-DES-CBC3-SHA:KRB5-IDEA-CBC-MD5:KRB5-DES-CBC3-MD5:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:ECDH-RSA-RC4-SHA:ECDH-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:PSK-RC4-SHA:KRB5-RC4-SHA:KRB5-RC4-MD5
```

```
> openssl version -a
OpenSSL 1.0.1e-fips 11 Feb 2013
built on: Mon May  9 08:07:32 UTC 2016
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx)
compiler: gcc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -DTERMIO -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  rdrand dynamic
```

```
>openssl ecparam -list_curves
  secp384r1 : NIST/SECG curve over a 384 bit prime field
  secp521r1 : NIST/SECG curve over a 521 bit prime field
  prime256v1: X9.62/SECG curve over a 256 bit prime field
```

**Comment by zaitsxl** [comment]
Hi fellas,

voting for the same problem. Platform is as follows 
CentOS Linux release 7.3.1611 (Core)

>openssl version -a
OpenSSL 1.0.1e-fips 11 Feb 2013
built on: Sun Nov  6 03:45:24 UTC 2016

>openssl ecparam -list_curves
secp384r1 : NIST/SECG curve over a 384 bit prime field
secp521r1 : NIST/SECG curve over a 521 bit prime field
prime256v1: X9.62/SECG curve over a 256 bit prime field

>openssl ciphers
ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-DSS-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:DHE-DSS-CAMELLIA256-SHA:ECDH-RSA-AES256-GCM-SHA384:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-RSA-AES256-SHA384:ECDH-ECDSA-AES256-SHA384:ECDH-RSA-AES256-SHA:ECDH-ECDSA-AES256-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA:PSK-AES256-CBC-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-DSS-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:DHE-RSA-SEED-SHA:DHE-DSS-SEED-SHA:DHE-RSA-CAMELLIA128-SHA:DHE-DSS-CAMELLIA128-SHA:ECDH-RSA-AES128-GCM-SHA256:ECDH-ECDSA-AES128-GCM-SHA256:ECDH-RSA-AES128-SHA256:ECDH-ECDSA-AES128-SHA256:ECDH-RSA-AES128-SHA:ECDH-ECDSA-AES128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:SEED-SHA:CAMELLIA128-SHA:PSK-AES128-CBC-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:EDH-DSS-DES-CBC3-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-ECDSA-DES-CBC3-SHA:DES-CBC3-SHA:IDEA-CBC-SHA:PSK-3DES-EDE-CBC-SHA:KRB5-IDEA-CBC-SHA:KRB5-DES-CBC3-SHA:KRB5-IDEA-CBC-MD5:KRB5-DES-CBC3-MD5:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:ECDH-RSA-RC4-SHA:ECDH-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:PSK-RC4-SHA:KRB5-RC4-SHA:KRB5-RC4-MD5

Client config is taken from example for P2P connections:
[fscp]
listen_on=0.0.0.0:12000
contact=my.peer.ip:12000
cipher_capability=aes256-gcm

[tap_adapter]
ipv4_address_prefix_length=192.168.0.2/24
dhcp_proxy_enabled=yes
dhcp_server_ipv4_address_prefix_length=192.168.0.0/24

[security]
signature_certificate_file=/etc/freelan/virginia.crt
signature_private_key_file=/etc/freelan/virginia.key
authority_certificate_file=/etc/freelan/ca.crt

Please give us any response, previous message lies for almost a year with no comments

Regards,
Alexander

**Comment by s-vincent** [comment]
Hello,

You can add the following to your [fscp] section:
elliptic_curve_capability=secp384r1

I have tested between a GNU/Linux Debian testing and Centos 7.3 and both peers manage to communicate OK.

@ereOn It seems that CentOS 7.x does not support secp571k1 elliptic curve (which is a default value), maybe we should check if system supports it before communicating with a peer with these capabilities or at least put a common elliptic curve as default value.

**Comment by ereOn** [comment]
If I remember correctly (it's been a while since I done that), I chose an elliptic curve that I deemed common enough to all implementations to mitigate those issues.

With you incoming PR the negotiation should always succeed (or fail with an explicit error).

**Comment by s-vincent** [comment]
@ereOn In fact the version of OpenSSL used is not the fault, it is CentOS that disables explicitely EC2M in the openssl.spec (to build RPM package) with no-ec2m flag.

```
./Configure \                                                                   
  --prefix=%{_prefix} --openssldir=%{_sysconfdir}/pki/tls ${sslflags} \         
  zlib enable-camellia enable-seed enable-tlsext enable-rfc3779 \               
  enable-cms enable-md2 enable-sctp \                                           
  no-mdc2 no-rc5 no-ec2m no-gost no-srp \                                       
  --with-krb5-flavor=MIT --enginesdir=%{_libdir}/openssl/engines \              
  --with-krb5-dir=/usr shared  ${sslarch} %{?!nofips:fips}
```

**Comment by s-vincent** [comment]
I update PR #137 to increases log level to warning and avoid an exception that exit application in case there are no cipher/elliptic curve match between two peers.

**Comment by s-vincent** [comment]
PR #137 has been merged.
