### ISSUE TITLE
DHCP lease time

### ISSUE THREAD

**Issue by ErickNogueira** [freelan-developers/freelan#110]
Hi,

I have Freelan running on Windows Server 2008 R2. Is it normal 60 minutes for DHCP lease time?

I got twice errors per hour at the server logs (DHCPNACK).

How can I extend the DHCP lease time for the TAP adapter?

**Comment by leggewie** [comment]
DHCP is done at the DHCP server level.  This is not a freelan bug.  Check with the DHCP server you have running locally.
