### ISSUE TITLE
UDP Hole Punching

### ISSUE THREAD

**Issue by Anime4000** [freelan-developers/freelan#111]
Beside using UPNP to allow incoming, UDP Hole Punching is great alternative to allow incoming connection, many application like Skype, Hamachi, TeamViewer VPN, etc... use this tricks to establish P2P connection.

to achieve this either using `relay` server or `pwnat`.

Tool:
[pwnat](https://github.com/samyk/pwnat)

**Comment by ereOn** [comment]
UDP hole punching is always (and has always been) implemented in FreeLAN.

There is nothing specific to do for that : you just have to make sure both peers try to reach each other via their configurations, and UDP hole punching kicks in if at least one of the routers is not a symmetric NAT.

Closing this. Feel free to reopen and give more precisions if that was not what you meant.

**Comment by chaserhkj** [comment]
Hi there,

I know it might be not that appropriate to comment on such an old issue but my question is strongly related with this.

I was trying to implement hybrid freelan network with a central server with public ip address and some clients behind some NATs. I hope the network could use udp hole punching to establish direct connections between peers when possible, and drop back to relaying through the central server if failed (like Hamachi).

But I'm not sure how to configure freelan to implement this kind of function.. Currently I have `relay_mode_enabled` set to `yes` on my server, and have `contact=server_address:12000` in all client configs with the https server disabled. Yet observing the delays between the clients I am not sure whether UDP hole punching kicks in or not...

What should be the current way of configuring this? Do I have to list the public IP addresses for all clients or enable the https server for these kinds of functionalities?

**Comment by richman1000000** [comment]
Hi! I have the same configuration.
you need to use  dynamic_contact

> On B client
>  dynamic_contact= A.cer

> on A cleint 
> dynamic_contact= B.cer

**Comment by s-vincent** [comment]
@chaserhkj 

> I hope the network could use udp hole punching to establish direct connections between peers when possible, and drop back to relaying through the central server if failed (like Hamachi).


What you say here it typically what does ICE (https://tools.ietf.org/html/rfc5245). It is not yet implemented in FreeLAN, see issue #146.
