### ISSUE TITLE
Windows TAP conflict

### ISSUE THREAD

**Issue by Anime4000** [freelan-developers/freelan#112]
on my VPS, I installed `isc-dhcp-server` and tell FreeLAN to use DHCP server instead proxy it.

Other application use Windows TAP and leaving their settings into `IP Manual Configuration`, and causing FreeLAN using that `IP Manual Configuration`.

I suggest that FreeLAN always set Windows TAP to `Auto Configuration`.

**Comment by jchevali** [comment]
I thought every application would use its own TAP device, configured independently from others.

**Comment by s-vincent** [comment]
@jchevali It is true for Linux and macOS but not for Windows unfortunately.

**Comment by s-vincent** [comment]
@Anime4000 As a workaround you can maybe install a dedicated TAP adapter just for FreeLAN and configure it via configuration file (option `name` in `fscp` section)

```
# The name of the tap adapter to use or create.                                 
#                                                                               
# On Windows, the GUID of an existing tap adapter is expected. It may be found  
# in the registry:                                                              
#                                                                               
# HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkCards  
#                                                                               
# If no name or an empty name is provided, the first available adapter will be  
# used.                                                                         
#                                                                               
# On UNIX, it is the name of the tap adapter to create. Depending on your       
# system, some names might be restricted, and something in the form of tapX     
# (where X is a positive number) is recommended.                                
#                                                                               
# If no name or an empty name is provided, a tap adapter will be created with   
# an available name.                                                            
#                                                                               
# Should you need to know it, you may get that name by specifying an up_script. 
#                                                                               
# Default: <empty>
```

**Comment by Anime4000** [comment]
I'll try...

**Comment by s-vincent** [comment]
@Anime4000 Any news on that ?

**Comment by Anime4000** [comment]
can not use DHCP server 😢 
freelan leave settings manual ip

**Comment by s-vincent** [comment]
@Anime4000 I added ipv4_dhcp option (false by default) in [tap_adapter] section to enable DHCP on TAP interface.

Can you please try revision 30b6f8c2d9c653304cb7e8738ee4529120f9bd90 with modified configuration file (ipv4_dhcp=true)?

**Comment by s-vincent** [comment]
No reply from several month, I believe it is fixed in my commits. I close this ticket. Feel free to reopen if any.
