### ISSUE TITLE
Configure using a certificate chain

### ISSUE THREAD

**Issue by paralin** [freelan-developers/freelan#114]
How can I use a certificate chain with Freelan?

I have the following chain:
- Root cert
- Intermediate 1
- Intermediate 2
- User certificate

I tried putting the 2 intermediates and root in order (top to bottom) in the `authority_certificate_file` file, but got the error when connecting `unable to get local issuer certificate`.

It made sense that freelan should be presenting the chain when attempting to connect, not just the topmost cert, so I put the entire chain inside `signature_certificate_file`, but this resulted it in just reading the first cert and getting a key mismatch.

So, how do you actually specify a certificate chain with freelan?

**Comment by ereOn** [comment]
This question was also asked on the mailing-list, so here is a copy of my reply.

Hi Christian,

How exactly did you put the intermediate and root certificates “in order” ?

Did you repeat the authority_certificate_file option in the configuration file or did you put them all in the same .crt file and referred to that file in the configuration ?

The latter should work (but not the first), if my memory serves me well.

If anything, do NOT put all of your chain in the signature_certificate_file as it is not supposed to contain it. Hence the error you got.

Let me know if that helps,
