### ISSUE TITLE
self-contact

### ISSUE THREAD

**Issue by richman1000000** [freelan-developers/freelan#115]
I do not know if this is issue, but I use 2 servers of freelan
One of them behind NAT and  get this error
freelan[497]: Ignoring PRESENTATION from 192.168.15.233:12000 as an active session currently exists with this host.

for some reason server tries to contact itself through NAT, and causes to go offline itself.
I've added never_contact=192.168.15.233 into configuration.
Now it is working but I get this message in logs
freelan[22994]: Ignoring HELLO_REQUEST from 192.168.15.233:12000 as it is a banned host.

**Comment by ereOn** [comment]
It could be that your NAT router somehow redirect unwanted traffic to your own host.

The solution you found makes sense and the second error message is actually expected in this case (but should not have any negative effect).
