### ISSUE TITLE
change install location for binary

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan#118]
SConstruct installs the binary to /bin.  Shouldn't that be /usr/sbin?

**Comment by ereOn** [comment]
I was expecting the Debian package to override that upon calling of the `SConstruct` script.

I don't mind changing the default though.

**Comment by leggewie** [comment]
Well, before having Debian deviate from the upstream default I'm trying to find out why you chose "bin as install location.

**Comment by leggewie** [comment]
Is there a reason to ever install it to /bin?

**Comment by ereOn** [comment]
I don't know. I should not matter. I don't mind aligning the defaults to something that eases Debian packaging as its the main target.

**Comment by s-vincent** [comment]
According to the [Filesystem Hierarchy Standard](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html), /bin is more for basic system binaries.

The default installation prefix should be either /usr/ or /usr/local/.

**Comment by ereOn** [comment]
Let's go for `/usr/local/` then. As I said, I picked this without a second thought.

**Comment by leggewie** [comment]
s-vincent is right, this isn't a Debian-specific thing.  This is about the FHS.

 /usr/local is usually for local installations.  Debian (and I believe other distros as well) do not install anything there.  It is an area for the user to install stuff in.  Distro packages live in /usr.  So, /usr/local is a sane default for personally compiled installations.  Debian will need to install to /usr.

**Comment by ereOn** [comment]
I don't think freelan uses `bin_prefix`, no.

**Comment by leggewie** [comment]
I don't see a way to override whatever default installation path there is in freelan for binaries.  How should I do it?

**Comment by s-vincent** [comment]
In master branch, compile with `make PRODUCT_PREFIX=/usr`.

In the debian/unstable branch, you can modify Makefile and use `scons install prefix=/usr` for install target. By the way PRODUCT_PREFIX stuff has been added in commit d782a42eaeecdce9b4377a7b41dc60b9fecca31c.

**Comment by s-vincent** [comment]
BTW I update the default installation prefix in master, now it /usr/local (see c825a878cdca3497b0de5e02f757ac94950ed547).

**Comment by s-vincent** [comment]
@ereOn @leggewie In fact bin_prefix is used (in master repository). I believe prefix is used for configuration file (in / by default so /etc/freelan.cfg)  and bin_prefix in /usr. So if we agree on putting all in /usr/local, I have to modify also BIN_PREFIX in the Makefile.

**Comment by ereOn** [comment]
Yep. Makes sense.

**Comment by s-vincent** [comment]
I am closing since I believe it is fixed in upstream as well as the ticket has information on how to override default options.
