### ISSUE TITLE
freelan and openvpn windows conflict

### ISSUE THREAD

**Issue by richman1000000** [freelan-developers/freelan#119]
This happens only on Windows systems.
If during installation of openvpn option   "add OpenVPN to path"  is enabled , (which is enabled by default),
freelan will not start, resulting in error.
OpenVPN folder contains files ssleay32.dll and libeay32.dll. FreeLAN have same names in it's folder.

I did disabled "add OpenVPN to path" and both FreeLAN and OpenVPN is working correctly

**Comment by ereOn** [comment]
This is sadly a limitation and very common problem on Windows: DLLs found in the PATH can be picked up directly - or like I suspect in that case: indirectly - by binaries and other DLLs resulting at times in incompatibility problems.

Aside from compiling freelan statically with its dependencies, what you did is the correct course of action to fix the issue.
