### ISSUE TITLE
Network status and log files - where to find them on windows, mac and linux? 

### ISSUE THREAD

**Issue by korzec** [freelan-developers/freelan#122]
Hi, 
I cannot find documentation on checking status of the freelan network and have trouble locating log files. 
I run on windows and mac. No luck compiling from source on Linux centos yet. 
I see some messages in mac log console,  but I hope there is more somewhere. 

Where are the log files? 

How to check network status? 

Thanks for any help!

**Comment by richman1000000** [comment]
Hi!
I only know how to collect logs in 2 systems.
In windows you can start it from console with parameters -d
In debian adding parameter -ddd into file /etc/default/freelan makes it to log lot of information.

**Comment by ereOn** [comment]
This has been answered I believe. I you still have a question, feel free to reopen.
