### ISSUE TITLE
Performance issue, if freelan manages thousands of logical connections.

### ISSUE THREAD

**Issue by helgebetzinger** [freelan-developers/freelan#124]
Hi,

we observed an exponentiall increase of cpu usage by freelan with the increasing number of  logically connection through a single, physically freelan link. We observed it only with increasing number pg logically connections, not with the increase of bandwith. So, we conclude an misbehaving algortithm within freelan while handling many connections. See the attached image with our measurements. The sum of of consumed bandwith is between 1-2 MBit / second. 

![img_17012017_110335](https://cloud.githubusercontent.com/assets/5240240/22016998/b3ba2d56-dca8-11e6-8068-b7208de73243.png)

Regards, Helge

**Comment by jenwe** [comment]
You can reproduce this with netcat, with these short scripts

script to receive:

```
#/bin/bash

i=12345
until [ $i -gt 17465 ]
do
netcat -vvlnp $i >/dev/null &
i=$[$i+1]
done
```

script to send:

```
#/bin/bash

i=12345
until [ $i -gt 16945 ]
do
dd if=/dev/zero bs=1K count=1G | pv -qL 1k | nc -vvn 10.2.0.11 $i &
i=$[$i+1]
done
```

**Comment by richman1000000** [comment]
Hi! I think your problem related to problem of freelan contacting itself.

In all my setups I've did that.
When you build configuration for the freelan instance, immediately  block it from contacting itself by adding same ip to never contact list in same configuration file.
"ipv4_address_prefix_length=10.18.0.10/23" - here you assign local ip
"never_contact=10.18.0.10" - here you deny contacting local ip.

**Comment by jenwe** [comment]
Thank you for the advice.
I tested your suggested configuration, but it didn't solve the problem.

**Comment by richman1000000** [comment]
The thing is - I had do add self block on all Freelan instances in my network.

**Comment by s-vincent** [comment]
Hi @helgebetzinger,

In last revisions we fixed some issues regarding memory and CPU consumption.

Can you please test again with last revision?

**Comment by s-vincent** [comment]
No answers for more than one years, closing.

Feel free to reopen if any.
