### ISSUE TITLE
Create VPN for NAT nodes with only a single reachable node.

### ISSUE THREAD

**Issue by ferdynice** [freelan-developers/freelan#125]
Nodes A and B are behind NAT. Only B is public reachable. (Using port forwarding for example). Is it currently possible to create a VPN between the two nodes?

If so, perhaps an addition to the documentation or FAQ would be nice.

If not, are there any plans to do so? Please have a look at PeerVPN, which supports this types of connection.

Thank you in advance.

**Comment by blackd** [comment]
Since B is publicly accessible you should just point A to it in the configuration by adding contact in [fscp] part of the configuration

[fscp]
contact=public_ip:open_port

**Comment by ferdynice** [comment]
Thanks.
