### ISSUE TITLE
Fail to compile against boost 1.63

### ISSUE THREAD

**Issue by wesx** [freelan-developers/freelan#126]
I'm currently trying to compile freelan on arch linux and struggled with the new boost version. On 1.63 they changed something on the optional syntax(https://svn.boost.org/trac/boost/ticket/12788) so that the build fails.  I added the suggested workaround and added "#define BOOST_NO_CXX11_UNIFIED_INITIALIZATION_SYNTAX". It compiles with these fixes, but afterwards it tries to use /usr/lib/libboost-{date_time,filesystem,iostreams,program_options,system,thread}.so.1.60.0 which are not on my present. When i make a symlink from libboost-*.so its working.
So i have two questions:
1. Should i commit the fix with BOOST_NO_CXX11_UNIFIED_INITIALIZATION_SYNTAX or do you want to fix it on an other way?
2. Is it possible to link to the libboost files without any version or with the correct version?

**Comment by wesx** [comment]
Here is the commit to fix the compile https://github.com/wesx/freelan/commit/41d2f2c3108fd7190dc18b271d467e1f4fe5535d

**Comment by ereOn** [comment]
@wesx I'll happily take a PR for this !

Thanks.

**Comment by wesx** [comment]
I created one. Do you have any idea of the 1.60 boost dependency?

**Comment by ereOn** [comment]
@wesx I lack information to answer reliably. One thing is certain though : do not mix boost versions.

If we explicitely rely on 1.63, then you'll have to download, compile & install that version on your system and refer to it (and not another one).

`INCLUDE`, `LIBRARY_PATH` and `LD_LIBRARY_PATH` can help with that.

**Comment by wesx** [comment]
ok, thanks. I will play around with that in the next days and see if i can get it to work with LIBRARAY, LIBRARY_PATH or LD_LIBRARY_PATH.

**Comment by wesx** [comment]
Thanks for your help. For the people with the same problem it works with`env LD_LIBRARAY_PATH=/usr/lib/libboost_data_time.so:/usr/lib/libboost_filesystem.so:/usr/lib/libboost_iostreams.so:/usr/libboost_program_options.so:/usr/lib/libboost_system.so:/usr/lib/libbosst_thread.so ./freelan`
