### ISSUE TITLE
Use brew packages on macOS

### ISSUE THREAD

**Issue by s-vincent** [freelan-developers/freelan#138]
If I understandard correctly dependencies (libssl, boost, ...) on macOS are built with .party files. But we can use brew packages (https://brew.sh/) instead.

I already have something working by doing the following steps:
- `brew install scons openssl boost `;
- Modify SConstruct/SConscript to add the brew's OpenSSL include/lib path to CXXFLAGS/LDFLAGS/LIBPATH as well as using boost_thread**-mt** instead of boost_thread.

WDYT ?

**Comment by s-vincent** [comment]
See PR #140 for detail.

**Comment by ereOn** [comment]
@s-vincent 

It makes a lot of sense to use the libraries as provided by the standard (or de-facto standard) packaging system on the platform, and Homebrew is the de-facto standard packaging system on OSX: so I'm all for it indeed.

**Comment by s-vincent** [comment]
PR #140 merged.
