### ISSUE TITLE
Adds unofficial debian packaging files

### ISSUE THREAD

**Issue by s-vincent** [freelan-developers/freelan#147]
As freelan-debian.git repository has been removed (and was a bit outdated), it still be interresting that we propose the possibility to generate debian package in main repository.

I think of users that want to use/test latest git revision of FreeLAN but do not want to compile on every machines and prefer to have debian package to install on them.

Base can be of course debian/unstable branch but adapted to use the master repository. A possible approach can be a specific branch (debian-master) tracked in master repository with git submodule.

@leggewie @ereOn WDYT ?

**Comment by leggewie** [comment]
I'm not a big fan of this.  This will generally lead to a support nightmare.  People who are skilled enough to compile on their own will do so.  People who are not skilled enough will be at a big risk to mess things up or have an already messed-up system to begin with.  This will be a support and troubleshooting nightmare.  We should not condone the idea of getting third-party packages. We should get stuff packaged quickly for debian instead.

**Comment by leggewie** [comment]
When necessary, I have backported individual upstream patches to Debian when they are fixing bugs.  That is a much better idea IMHO.

**Comment by s-vincent** [comment]
It makes senses. I close the issue.
