### ISSUE TITLE
freelan need additional connection status check

### ISSUE THREAD

**Issue by richman1000000** [freelan-developers/freelan#158]
Hi!
currently freelan have a problem with unstable connection.
If connection between 2 computers is broken freelan does not tries to establish new one.
The fallen out computer can be offline in freelan network for days.

see in the video the way to reproduce it 
https://yadi.sk/d/U3Z7QK7Aing6D/2017-08-29_10-37-14.mp4

PS.
I use latest compiled version from  https://github.com/freelan-developers/freelan/archive/master.zip

**Comment by richman1000000** [comment]
In addition if I will restart client on other client this errors occur. 

on this error system must try to check current session and if it is not working - drop and create new one
Ignoring PRESENTATION from 10.17.0.103:12000 as an active session currently exists with this host.

system must send new session request instead of ignoring
Received a data message from 10.17.0.254:12000 but no session exists. Ignoring.

**Comment by leggewie** [comment]
I tried, but was unable to reproduce this issue in the following way.  I have two computers with a PSK-VPN.  I verify I can ping to and from both computers.  I keep ping running from computer 1 to computer 2 and disconnect the wifi on computer 1.  After about 5 seconds, I reconnect the wifi and after the net connection is established, freelan delivers the pings across the VPN again successfully.  Are you having longer interruptions than that?  We need more info to reproduce.

**Comment by richman1000000** [comment]
here few configuration points  that can be in effect
- linux server is in relay_mode=yes
- linux relay server  **does not contact anybody**, always contacted by all clients

**Comment by richman1000000** [comment]
I seems like problem is located on "server" side.
Which is receiving contacts but not contact anybody.

**Comment by richman1000000** [comment]
In this version  freelan 2.1-1 works as expected

**Comment by richman1000000** [comment]
Debian 9.4 x64

in file /etc/default/freelan
set **DAEMON_OPTS="-ddd "**

to separate freelan log into separated log file 
in file /etc/rsyslog.d/freelan.conf 
```
if ($programname=='freelan') then /var/log/freelan.log
& ~

```
now you can monitor content of file /var/log/freelan.log

**Comment by s-vincent** [comment]
I tried the following cases with physical machine Linux and a VM Windows:
1) 
- Launch two peers A and B;
- A contacts no one;
- B contacts A;
- A is shutdown manually and restarted;
- A receives some message "Received a data message from 192.168.XXX.XXX:12000 but no session exists. Ignoring."
- After 30 seconds, previous B session with A timeout ;
- As B is designed to contact A, after some time it does it and succeeded to establish connection.

2) 
- Launch two peers A and B;
- A contacts no one;
- B contacts A;
- B is shutdown manually and restarted;
- B receives some message "Ignoring PRESENTATION from 192.168.XXX.XXX:12000 as an active session currently exists with this host"
- After 30 seconds, previous A session with B timeout ;
- As B is designed to contact A, after some time it does it and succeeded to establish connection.

So in any case, there is the session timeout that saves us to clear old sessions and restart them. I tried in PSK mode as well with certificates.

@richman1000000 is it still happening on your setup ?

**Comment by richman1000000** [comment]
ya, in newer version connection drops after 30 seconds.
since this resolves the issue I think you can make this as enchantment cause  30 seconds downtime is not good for router.
