### ISSUE TITLE
How to fix " Invalid route metric" error?

### ISSUE THREAD

**Issue by bhzhu203** [freelan-developers/freelan#159]
## Node A

```
freelan  --security.passphrase "abc"  --tap_adapter.metric=1000  --tap_adapter.ipv4_address_prefix_length 10.8.0.3/24 -d -f
```

Output:

> 2017-09-03T21:14:44.819692 [WARNING] Warning ! No configuration file specified and none found in the environment.
> 2017-09-03T21:14:44.819873 [WARNING] Looked up locations were:
> 2017-09-03T21:14:44.819897 [WARNING] - "/root/.freelan/freelan.cfg"
> 2017-09-03T21:14:44.819915 [WARNING] - "/usr/local/etc/freelan/freelan.cfg"
> 2017-09-03T21:14:44.820013 [INFORMATION] Deriving pre-shared key from passphrase...
> 2017-09-03T21:14:44.829287 [DEBUG] Opening core...
> 2017-09-03T21:14:44.829328 [INFORMATION] Enabling pre-shared key authentication.
> 2017-09-03T21:14:44.829350 [INFORMATION] Starting FSCP server...
> 2017-09-03T21:14:44.829585 [WARNING] Elliptic curve not supported: sect571k1
> 2017-09-03T21:14:44.837720 [WARNING] Elliptic curve not supported: sect571k1
> 2017-09-03T21:14:44.845539 [IMPORTANT] Core set to listen on: 0.0.0.0:12000
> 2017-09-03T21:14:44.845577 [INFORMATION] Building CA store...
> 2017-09-03T21:14:44.845655 [INFORMATION] Discovering UPnP IGD gateways.
> 2017-09-03T21:14:52.855439 [ERROR] UPnP discovery/port mapping failed: Success
> 2017-09-03T21:14:52.855508 [INFORMATION] FSCP server started.
> 2017-09-03T21:14:52.855990 [IMPORTANT] Tap adapter "tap0" opened in mode tap with a MTU set to: 1446
> 2017-09-03T21:14:52.856024 [IMPORTANT] MSS override enabled with a value of: 1392
> 2017-09-03T21:14:52.856051 [INFORMATION] IPv4 address: 10.8.0.3/24
> 2017-09-03T21:14:52.856082 [INFORMATION] No IPv6 address configured.
> 2017-09-03T21:14:52.858023 [INFORMATION] Putting interface into the connected state.
> 2017-09-03T21:14:52.859945 [INFORMATION] The DHCP proxy is enabled.
> 2017-09-03T21:14:52.859977 [INFORMATION] Not advertising any routes.
> 2017-09-03T21:14:52.859995 [INFORMATION] Not advertising any DNS servers.
> 2017-09-03T21:14:52.860219 [DEBUG] Core opened.
> 2017-09-03T21:14:52.860299 [INFORMATION] Using 10 thread(s).
> 2017-09-03T21:14:52.860335 [IMPORTANT] Execution started.
> 2017-09-03T21:14:52.860353 [INFORMATION] Starting tap adapter's thread...
> 2017-09-03T21:14:52.860580 [DEBUG] Thread #0 started.
> 2017-09-03T21:14:52.864913 [DEBUG] Thread #1 started.
> 2017-09-03T21:14:52.864936 [DEBUG] Thread #2 started.
> 2017-09-03T21:14:52.865172 [DEBUG] Thread #3 started.
> 2017-09-03T21:14:52.865313 [DEBUG] Thread #4 started.
> 2017-09-03T21:14:52.865466 [DEBUG] Thread #5 started.
> 2017-09-03T21:14:52.865586 [DEBUG] Thread #6 started.
> 2017-09-03T21:14:52.865687 [DEBUG] Thread #7 started.
> 2017-09-03T21:14:52.870771 [DEBUG] Thread #8 started.
> 2017-09-03T21:14:52.870780 [DEBUG] Thread #9 started.
> 2017-09-03T21:15:25.429653 [DEBUG] Received HELLO_REQUEST from 192.168.20.248:12000.
> 2017-09-03T21:15:25.430576 [TRACE] Received a SESSION_REQUEST from 192.168.20.248:12000 but no presentation is available. Ignoring.
> 2017-09-03T21:15:25.430683 [DEBUG] Received PRESENTATION from 192.168.20.248:12000 using pre-shared key authentication.
> 2017-09-03T21:15:25.430729 [INFORMATION] Accepting PRESENTATION from 192.168.20.248:12000 for pre-shared key authentication: first presentation.
> 2017-09-03T21:15:25.430761 [DEBUG] Sending SESSION_REQUEST to 192.168.20.248:12000.
> 2017-09-03T21:15:25.430887 [TRACE] Sending session request message to 192.168.20.248:12000 (next_session_number: 0, local_host_identifier: 84e59dade956e7c4f1c0ebeb2231e069c2073093ba3a2474ca7cba0405872d73)
> 2017-09-03T21:15:25.435884 [DEBUG] Received SESSION from 192.168.20.248:12000 (default: accept).
> 2017-09-03T21:15:25.435934 [DEBUG] Cipher suite: ecdhe_rsa_aes256_gcm_sha384
> 2017-09-03T21:15:25.435954 [DEBUG] Elliptic curve: secp384r1
> 2017-09-03T21:15:25.435985 [TRACE] Received a SESSION from 192.168.20.248:12000 with session number 0 but no session was prepared yet. Preparing a new one.
> 2017-09-03T21:15:25.446588 [TRACE] Session established with 192.168.20.248:12000. Sending acknowledgement session message back.
> 2017-09-03T21:15:25.446626 [TRACE] Sending session message to 192.168.20.248:12000 (session number: 0, cipher suite: ecdhe_rsa_aes256_gcm_sha384, elliptic curve: secp384r1).
> 2017-09-03T21:15:25.446708 [IMPORTANT] Session established with 192.168.20.248:12000.
> 2017-09-03T21:15:25.446734 [INFORMATION] Cipher suite: ecdhe_rsa_aes256_gcm_sha384
> 2017-09-03T21:15:25.446752 [INFORMATION] Elliptic curve: secp384r1
> 2017-09-03T21:15:25.446857 [DEBUG] Sending routes request to 192.168.20.248:12000.
> 2017-09-03T21:15:25.446995 [ERROR] Fatal exception occurred in thread #3: Invalid route metric
> 2017-09-03T21:15:25.447024 [DEBUG] Closing core...
> 2017-09-03T21:15:25.447120 [INFORMATION] Tap adapter's thread is now stopped.
> 2017-09-03T21:15:25.448746 [TRACE] Received a SESSION from 192.168.20.248:12000 with session number 0 and cipher suite ecdhe_rsa_aes256_gcm_sha384. A session currently exists and has the same number and cipher suite. Ignoring.
> 2017-09-03T21:15:25.449019 [DEBUG] Received routes request from 192.168.20.248:12000. Replying with version 0: 
> 2017-09-03T21:15:25.449059 [DEBUG] Sending routes and DNS servers to 192.168.20.248:12000: version 0 (), ().
> 2017-09-03T21:15:25.486678 [INFORMATION] Closing FSCP server...
> 2017-09-03T21:15:25.486806 [INFORMATION] FSCP server closed.
> 2017-09-03T21:15:25.486832 [DEBUG] Core closed.
> 2017-09-03T21:15:25.486884 [DEBUG] Thread #6 stopped.
> 2017-09-03T21:15:25.486915 [DEBUG] Thread #8 stopped.
> 2017-09-03T21:15:25.486957 [DEBUG] Thread #3 stopped.
> 2017-09-03T21:15:25.487057 [DEBUG] Thread #7 stopped.
> 2017-09-03T21:15:25.487096 [DEBUG] Thread #5 stopped.
> 2017-09-03T21:15:25.487122 [DEBUG] Thread #4 stopped.
> 2017-09-03T21:15:25.487145 [DEBUG] Thread #9 stopped.
> 2017-09-03T21:15:25.487187 [DEBUG] Thread #2 stopped.
> 2017-09-03T21:15:25.487198 [DEBUG] Thread #0 stopped.
> 2017-09-03T21:15:25.487124 [DEBUG] Thread #1 stopped.
> 2017-09-03T21:15:25.487918 [IMPORTANT] Execution stopped.
> 

## Node B

```
freelan  --security.passphrase "abc" --fscp.contact 192.168.2.204:12000  --tap_adapter.ipv4_address_prefix_length 10.8.0.2/24 -d -f  --tap_adapter.metric=1000
```

> 2017-09-03T21:29:23.692133 [WARNING] Warning ! No configuration file specified and none found in the environment.
> 2017-09-03T21:29:23.692248 [WARNING] Looked up locations were:
> 2017-09-03T21:29:23.692261 [WARNING] - "/root/.freelan/freelan.cfg"
> 2017-09-03T21:29:23.692271 [WARNING] - "/usr/local/etc/freelan/freelan.cfg"
> 2017-09-03T21:29:23.692327 [INFORMATION] Deriving pre-shared key from passphrase...
> 2017-09-03T21:29:23.697548 [DEBUG] Opening core...
> 2017-09-03T21:29:23.697570 [INFORMATION] Enabling pre-shared key authentication.
> 2017-09-03T21:29:23.697583 [INFORMATION] Starting FSCP server...
> 2017-09-03T21:29:23.697712 [WARNING] Elliptic curve not supported: sect571k1
> 2017-09-03T21:29:23.702169 [WARNING] Elliptic curve not supported: sect571k1
> 2017-09-03T21:29:23.706349 [IMPORTANT] Core set to listen on: 0.0.0.0:12000
> 2017-09-03T21:29:23.706371 [INFORMATION] Building CA store...
> 2017-09-03T21:29:23.706413 [INFORMATION] Discovering UPnP IGD gateways.
> 2017-09-03T21:29:31.715712 [ERROR] UPnP discovery/port mapping failed: Success
> 2017-09-03T21:29:31.715762 [DEBUG] Resolving 192.168.2.204:12000 for potential contact...
> 2017-09-03T21:29:31.715803 [INFORMATION] FSCP server started.
> 2017-09-03T21:29:31.716122 [IMPORTANT] Tap adapter "tap0" opened in mode tap with a MTU set to: 1446
> 2017-09-03T21:29:31.716150 [IMPORTANT] MSS override enabled with a value of: 1392
> 2017-09-03T21:29:31.716165 [INFORMATION] IPv4 address: 10.8.0.2/24
> 2017-09-03T21:29:31.716183 [INFORMATION] No IPv6 address configured.
> 2017-09-03T21:29:31.717281 [INFORMATION] Putting interface into the connected state.
> 2017-09-03T21:29:31.718326 [INFORMATION] The DHCP proxy is enabled.
> 2017-09-03T21:29:31.718371 [INFORMATION] Not advertising any routes.
> 2017-09-03T21:29:31.718382 [INFORMATION] Not advertising any DNS servers.
> 2017-09-03T21:29:31.718550 [DEBUG] Core opened.
> 2017-09-03T21:29:31.718595 [INFORMATION] Using 10 thread(s).
> 2017-09-03T21:29:31.718608 [IMPORTANT] Execution started.
> 2017-09-03T21:29:31.718645 [INFORMATION] Starting tap adapter's thread...
> 2017-09-03T21:29:31.719177 [DEBUG] Thread #0 started.
> 2017-09-03T21:29:31.719294 [DEBUG] Thread #1 started.
> 2017-09-03T21:29:31.719339 [DEBUG] No session exists with 192.168.2.204:12000 (at 192.168.2.204:12000). Contacting...
> 2017-09-03T21:29:31.719423 [DEBUG] Sending HELLO to 192.168.2.204:12000
> 2017-09-03T21:29:31.719445 [DEBUG] Thread #2 started.
> 2017-09-03T21:29:31.719562 [DEBUG] Thread #3 started.
> 2017-09-03T21:29:31.719768 [DEBUG] Thread #4 started.
> 2017-09-03T21:29:31.720298 [DEBUG] Thread #5 started.
> 2017-09-03T21:29:31.720465 [DEBUG] Thread #6 started.
> 2017-09-03T21:29:31.720623 [DEBUG] Thread #7 started.
> 2017-09-03T21:29:31.720751 [DEBUG] Thread #8 started.
> 2017-09-03T21:29:31.720792 [DEBUG] Thread #9 started.
> 2017-09-03T21:29:31.721388 [DEBUG] Received PRESENTATION from 192.168.2.204:12000 using pre-shared key authentication.
> 2017-09-03T21:29:31.721412 [INFORMATION] Accepting PRESENTATION from 192.168.2.204:12000 for pre-shared key authentication: first presentation.
> 2017-09-03T21:29:31.721428 [DEBUG] Sending SESSION_REQUEST to 192.168.2.204:12000.
> 2017-09-03T21:29:31.721507 [TRACE] Sending session request message to 192.168.2.204:12000 (next_session_number: 0, local_host_identifier: 5b56bdfd7310c5746dab4476c4d34c02cbb551baf87f9e4b677237e4a4050bee)
> 2017-09-03T21:29:31.721519 [DEBUG] Received HELLO_RESPONSE from 192.168.2.204:12000 at 192.168.2.204:12000. Latency: 00:00:00.000716
> 2017-09-03T21:29:31.722440 [DEBUG] Received SESSION_REQUEST from 192.168.2.204:12000 (default: accept).
> 2017-09-03T21:29:31.722461 [DEBUG] Cipher suites capabilities: ecdhe_rsa_aes256_gcm_sha384 ecdhe_rsa_aes128_gcm_sha256
> 2017-09-03T21:29:31.722482 [DEBUG] Elliptic curve capabilities: secp384r1
> 2017-09-03T21:29:31.722501 [TRACE] Received a SESSION_REQUEST from 192.168.2.204:12000 with session number 0 and cipher suite ecdhe_rsa_aes256_gcm_sha384_secp384r1. No current session exist: preparing one and sending it.
> 2017-09-03T21:29:31.726772 [TRACE] Sending session message to 192.168.2.204:12000 (session number: 0, cipher suite: ecdhe_rsa_aes256_gcm_sha384, elliptic curve: secp384r1).
> 2017-09-03T21:29:31.738195 [DEBUG] Received SESSION from 192.168.2.204:12000 (default: accept).
> 2017-09-03T21:29:31.738213 [DEBUG] Cipher suite: ecdhe_rsa_aes256_gcm_sha384
> 2017-09-03T21:29:31.738224 [DEBUG] Elliptic curve: secp384r1
> 2017-09-03T21:29:31.739648 [TRACE] Session established with 192.168.2.204:12000. Sending acknowledgement session message back.
> 2017-09-03T21:29:31.739670 [TRACE] Sending session message to 192.168.2.204:12000 (session number: 0, cipher suite: ecdhe_rsa_aes256_gcm_sha384, elliptic curve: secp384r1).
> 2017-09-03T21:29:31.739709 [IMPORTANT] Session established with 192.168.2.204:12000.
> 2017-09-03T21:29:31.739724 [INFORMATION] Cipher suite: ecdhe_rsa_aes256_gcm_sha384
> 2017-09-03T21:29:31.739734 [INFORMATION] Elliptic curve: secp384r1
> 2017-09-03T21:29:31.739776 [DEBUG] Sending routes request to 192.168.2.204:12000.
> 2017-09-03T21:29:31.739870 [ERROR] Fatal exception occurred in thread #5: Invalid route metric
> 2017-09-03T21:29:31.739886 [DEBUG] Closing core...
> 2017-09-03T21:29:31.739956 [INFORMATION] Tap adapter's thread is now stopped.
> 2017-09-03T21:29:31.740016 [DEBUG] Received routes request from 192.168.2.204:12000. Replying with version 0: 
> 2017-09-03T21:29:31.740042 [DEBUG] Sending routes and DNS servers to 192.168.2.204:12000: version 0 (), ().
> 2017-09-03T21:29:31.773438 [INFORMATION] Closing FSCP server...
> 2017-09-03T21:29:31.773508 [INFORMATION] FSCP server closed.
> 2017-09-03T21:29:31.773522 [DEBUG] Core closed.
> 2017-09-03T21:29:31.773542 [DEBUG] Thread #5 stopped.
> 2017-09-03T21:29:31.773585 [DEBUG] Thread #9 stopped.
> 2017-09-03T21:29:31.773587 [DEBUG] Thread #0 stopped.
> 2017-09-03T21:29:31.773597 [DEBUG] Thread #4 stopped.
> 2017-09-03T21:29:31.773639 [DEBUG] Thread #3 stopped.
> 2017-09-03T21:29:31.773638 [DEBUG] Thread #6 stopped.
> 2017-09-03T21:29:31.773586 [DEBUG] Thread #2 stopped.
> 2017-09-03T21:29:31.773610 [DEBUG] Thread #7 stopped.
> 2017-09-03T21:29:31.773981 [DEBUG] Thread #8 stopped.
> 2017-09-03T21:29:31.774000 [DEBUG] Thread #1 stopped.
> 2017-09-03T21:29:31.774173 [IMPORTANT] Execution stopped.
> 

Node A starts first , then node B connects to A. Finally node A and B both exit with an "Invalid route metric"error.

FreeLAN version: `freelan 2.1.0 (2.1) Thu 31 Aug 2017   CentOS6`

**Comment by bhzhu203** [comment]
Removing  "tap_adapter.metric" and using default that  also no use.

**Comment by s-vincent** [comment]
After looking a bit in the code, the metric is not taken into account on Unix OS and is always 0. Maybe older kernels (such as CentOS ones which is IIRC from a 2.6 series) do not like that.

It does not seems to hurt recent Debian distributions and CentOS 7 though.

**Comment by ereOn** [comment]
@s-vincent If the metric is ignored, it's probably because at the time I implemented the mechanism I didn't see how to honor that parameter with the existing APIs.

There is no valid reason as to why it should remain that way if newer kernels do support it. Perhaps my assertion was wrong from the beginning (but it's been too long for me to remember the context).

**Comment by s-vincent** [comment]
I made some investigation and it appears we don't handle RTA_MЕTRICS correctly. Waiting for that, I disable exception throwing.

@bhzhu203 Can you give a try to latest revision (1cf517bfc104c97a1eeb5a0f94becd0b8999ceaa) ?

**Comment by Bertsz** [comment]
https://github.com/freelan-developers/freelan/commit/1cf517bfc104c97a1eeb5a0f94becd0b8999ceaa
I was trying to run a server without a tun/tap device as a relay on debian and this seemed to fix the crash for me. Thanks a bunch!

**Comment by s-vincent** [comment]
I believe this bug is fixed.

About 1cf517b, metrics value on Linux is not used anyway so no worry, it will not break anything.

Feel free to reopen if any.
