### ISSUE TITLE
FTBFS with glibc 2.25

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan#164]
freelan FTBFS against glibc 2.25.  This will result in it being dropped from Debian testing eventually.

https://bugs.debian.org/882733
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/freelan.html

**Comment by s-vincent** [comment]
It is already fixed in master / 2.1 tag.

See #128.

**Comment by s-vincent** [comment]
@leggewie Feel free to backport the patch in the Debian 2.0 version.

On a side note I presume we can go for a 2.1 official release (@ereOn  ?).

**Comment by ereOn** [comment]
@s-vincent I suppose we can yes. I still couldn't test on Windows (no progress). Does it work for you ?

**Comment by s-vincent** [comment]
@leggewie The freelan 2.1 tag is out.
