### ISSUE TITLE
Client server example

### ISSUE THREAD

**Issue by vetash** [freelan-developers/freelan#165]
Hello! 
i have three nodes with freelan and trying to set them to the one broadcast domain.

First node is server accesible from host A and B. A and B is behind NAT
Server:
`freelan --security.passphrase "my secret" --tap_adapter.ipv4_address_prefix_length 9.0.0.1/24 --server.enabled=yes --server.listen_on=0.0.0.0:443`
Node A:
`freelan --security.passphrase "my secret" --fscp.contact 192.168.20.120:12000 --tap_adapter.ipv4_address_prefix_length 9.0.0.2/24 --client.server_endpoint=192.168.20.120:443`
Node B:
`freelan --security.passphrase "my secret" --fscp.contact 192.168.20.120:12000 --tap_adapter.ipv4_address_prefix_length 9.0.0.3/24 --client.server_endpoint=192.168.20.120:443`

Both A and B can be reached from server by ping but not each other.

**Comment by richman1000000** [comment]
Hello!
You can do this using  certificate based vpn 
on client A in file /etc/freelan/freelan.cfg 
**dynamic_contact_file=B.cer
never_contact=9.0.0.2**
on client B in file /etc/freelan/freelan.cfg 
**dynamic_contact_file=A.cer
never_contact=9.0.0.3**
on server in file  /etc/freelan/freelan.cfg 
**never_contact=9.0.0.1**

**Comment by s-vincent** [comment]
@vetash I think you should set the following --switch.relay_mode_enabled=yes on the server node to enable relaying frames from client nodes to others.

**Comment by leggewie** [comment]
@vetash Did this fix the problem for you?

**Comment by richman1000000** [comment]
I will test this again

**Comment by s-vincent** [comment]
@vetash have you got time to check this ?

**Comment by s-vincent** [comment]
Three month witout news, I close.

Feel free to reopen if any.
