### ISSUE TITLE
Packet filtering

### ISSUE THREAD

**Issue by PalmaNicola** [freelan-developers/freelan#169]
Hello!
I would like to customize freelan to allow communication only to/from specific addresses and ports.
I made a few attempts with filters objects in core.cpp (like m_tcpv4_filter), but it doesn't seem right, ports have different numbers and frames passing by seem to be only from outbound calls.

![image](https://user-images.githubusercontent.com/22478840/38993460-ff46ec70-43e3-11e8-92b6-6b37359926d6.png)

Which classes should I edit?
Thanks for your attention. I’m looking forward to your reply.

**Comment by richman1000000** [comment]
"to/from specific addresses"
I don't think this is good idea to implement this into application itself.
All firewalls do ip:port filtering. Use firewall.

**Comment by s-vincent** [comment]
I agree with richman1000000, it is will be much better and more efficient to do the filtering in iptables / ip6tables directly.

**Comment by s-vincent** [comment]
I close the issue since firewall setup should be the way to go.
