### ISSUE TITLE
Question about the freelan server feature

### ISSUE THREAD

**Issue by chaserhkj** [freelan-developers/freelan#172]
Hi there,

I was trying to configure freelan on my server to provide me and my friends some Hamachi-like VPN service which could use direct connection if possible and use relays if not. However, the documentation seems to be a bit chaotic and scattered. I've read changelogs, some issues, example configurations, github wikis, but still could not found a full description of how the (HTTPS) freelan server works. I tried to summarize it but not sure with myself. I'll put it here, could any of the devs confirm that the server works as I expected?

- if `server.enabled` is yes, the server would be started as https server using `server_private_key_file` and `server_certificate_file` to do tls
- if `client.enabled` is yes, and `passphrase`, `signature_certificate_file`, `signature_private_key_file` are not supplied, the client would generate a cert and a key, asking the server to sign the cert through a https session
- server would authenticate the client and on success, sign the cert using the CA cert and key and assign it to the client for p2p validation. All clients must have CA cert to validate each other
- Client would then register its IP address with the server using `public_endpoint` address
- Server would share all registered clients with each other.
- client would contact any peers supplied in `contact` directives, any peers identified by the cert files in `dynamic_contact_file` directives, plus any other registered clients pushed by the server

And:

- p2p connection would try a UDP hole punching if any one side is behind NAT (This is my main concern as stated in #111 , while most of the clients in my use case are behind NAT)
- IP address assigning is not involved, clients have to do it themselves.

Am I in the right understanding for how the freelan server works? Please do point out any errors I might have made, thanks!

**Comment by richman1000000** [comment]
freelan working in peer-to-peer mode. Server is only issuing certificates to clients of network and not participating in it itself.

**Comment by chaserhkj** [comment]
@richman1000000 Thanks for the reply! I know that the freelan server may not participate in VPN traffic, but my focus is whether it helps clients to find each other, like the tracker server in a bittorrent network?

**Comment by richman1000000** [comment]
I don't remember exactly, but I think it is helps client to find each other.

**Comment by s-vincent** [comment]
@chaserhkj Quickly seen the code, it is more or less what you said. Peers can request specific contacts from server or all of them.

But one important things is currently HTTPS server is not built by default due to licensing issue with libmongoose (as it violates GPL).

On a side note Freelan supports also UPnP to open port on router. And ticket to implement ICE feature is already there.

**Comment by s-vincent** [comment]
I believe question has been asked.

Feel free to reopen if it isn't.
