### ISSUE TITLE
Does not compile on FreeBSD 11.X

### ISSUE THREAD

**Issue by unix-usr** [freelan-developers/freelan#173]
Attempted to build on FreeBSD - required repeated changes to os.hpp - line 86/87 with errors about attempting to re-define #BSD as it is already defined in params.h.

Once I was passed that it's getting hung up linking iconv plus - have installed the library and have tried make-ing with CFLAGS set appropriately, will keep attempting and update this issue if I am able to succeed.

**Comment by s-vincent** [comment]
@unix-usr do you use gcc or clang to compile ?

**Comment by unix-usr** [comment]
Trying with clang first - tried make and gnu make, will try with gcc and see/report back. Ideally I'd like to help contribute and get this into the FreeBSD ports collection.

**Comment by s-vincent** [comment]
I have fixed the redefine BSD stuff in revision b4b4c6d6ff6b0c4a0de65eae2be1a6f401757833.

Compilation succeeded on a fresh FreeBSD 11.2 install with the following commands:
pkg install git miniupnpc scons boost-all curl
git clone https://github.com/freelan-developers/freelan.git
cd freelan
make

@unix-usr Can you please test again with this configuration and the latest revision ?

**Comment by unix-usr** [comment]
I tried the above - working fine now :) - FreeBSD 11.2-RELEASE / amd64 / clang for the record... now I've just got to figure out how to use it and see if I can somehow cross-compile a package for debian/arm to install on Ubiquiti ER-X units.
