### ISSUE TITLE
scons install broken

### ISSUE THREAD

**Issue by buzo-ffm** [freelan-developers/freelan#176]
I packaged freelan for Arch Linux ([here](https://aur.archlinux.org/packages/freelan-git/)), but had problems with the packaging step: The binary was not installed in */usr/bin*. Adding [this patch](https://aur.archlinux.org/cgit/aur.git/tree/fix-build.diff?h=freelan-git) fixed it.

The patch also fixes the installation directory for the man page: */usr/share/man* instead of */usr/man*.

**Comment by s-vincent** [comment]
Patch integrated in master branch (76dc44689192603b37ae8edad682c13d1d3e0e17).

**Comment by buzo-ffm** [comment]
Thanks!
