### ISSUE TITLE
Minor edits for packaging/rpm

### ISSUE THREAD

**Issue by klayman** [freelan-developers/freelan#183]
- Version should be 2.2 in `packaging/rpm/freelan.spec`:
`%{!?version:%define version 2.2}`

- `packaging/rpm/README.md` should list `help2man` in the dependencies.

**Comment by s-vincent** [comment]
Thank you for your report.

We will fix that ASAP.

**Comment by s-vincent** [comment]
Done in 8c0e87266a0d3f2737c7e47e33ca55565a0f031c.
