### ISSUE TITLE
Help with configuration of VLAN

### ISSUE THREAD

**Issue by Najsr** [freelan-developers/freelan#184]
Hello there, I am really new into VPN stuff and I found out about this software recently but I haven't been able to setup it correctly. I am looking into a setup where there would be server which would create a VLAN for all clients connected (without access to internet via the server) with password config - Not planning to use it with any sensitive data, just wanting to get rid of hamachi's unreliability.
Is there anyone who could help me setup sample config for server and for client?

Thanks,
David.

**Comment by richman1000000** [comment]
you can bridge tap0 with eth0.1 - this will do the trick

**Comment by s-vincent** [comment]
@Najsr Does suggestion from @richman1000000 answers your issue ?

**Comment by s-vincent** [comment]
I am closing this since no reply. Feel free to reopen if any.
