### ISSUE TITLE
[solved] Debian 9 - [ERROR] in security.signature_certificate_file: unable to load certificate at

### ISSUE THREAD

**Issue by ds2k5** [freelan-developers/freelan#187]
Hello,
using Debian9 amd64 FreeLAN 2.0-2 (from debian repo)

here my config:

/etc/freelan/freelan.cfg

```
[fscp]
listen_on=0.0.0.0:12000
contact=192.168.10.1:12000
cipher_capability=aes256-gcm

[tap_adapter]
ipv4_address_prefix_length=192.168.222.2/24
dhcp_proxy_enabled=yes
dhcp_server_ipv4_address_prefix_length=192.168.222.0/24

[security]
signature_certificate_file="/etc/freelan/spieler2.crt"
signature_private_key_file="/etc/freelan/spieler2.key"
authority_certificate_file="/etc/freelan/ca.crt"
```

When try to start in foreground got this error:

# freelan -f -d
```
```
2019-02-14T10:45:34.966845 [INFORMATION] Reading configuration file at: "//etc/freelan/freelan.cfg"

2019-02-14T10:45:34.968165 [ERROR] in security.signature_certificate_file: unable to load certificate at "//etc/etc/freelan/spieler2.crt" (No such file or directory)
```

# ls -la /etc/freelan/spieler2.crt
-rw------- 1 root root 4438 Feb 14 10:34 /etc/freelan/spieler2.crt

What is wrong why is "etc" twice set ? ("//etc/etc/freelan/spieler2.crt")

**Comment by richman1000000** [comment]
signature_certificate_file="/etc/freelan/spieler2.crt"
change to 
signature_certificate_file=spieler2.crt

**Comment by ds2k5** [comment]
thank you very much!
