### ISSUE TITLE
VPN Tunnel - connect only one IP

### ISSUE THREAD

**Issue by ds2k5** [freelan-developers/freelan#188]
Hello,
sorry about my english, hope the picture helps....
Wann build a VPN with 4 or more Clients with Raspberry PI.
Each RPI offer a WiFI to connect.
One RPI is Server and the other are clients.
Target is that all can connect ony one IP, for example: 192.168.254.253
so that there is running a Appliaction that all wanna use.

https://www.bilder-upload.eu/bild-4a6a40-1550236214.jpg.html

172.16.1.0/24 insted of Internet WAN Adresses, because build it in a virtual enviorment
for testing.

But my Problem is that only the RPIs can ping the 192.168.254.253 but not Devices that connected to
RPI over WiFI.

Here is my config.

**Server:**

```
[fscp]
listen_on=0.0.0.0:12000
cipher_capability=aes256-gcm

[tap_adapter]
ipv4_address_prefix_length=192.168.254.253/24

[security]
signature_certificate_file="spieler1.crt"
signature_private_key_file="spieler1.key"
authority_certificate_file="ca.crt"

```

**Client1:**
```

[fscp]
contact=172.16.1.1:12000
cipher_capability=aes256-gcm

[tap_adapter]
ipv4_address_prefix_length=192.168.254.2/24

[security]
signature_certificate_file="spieler2.crt"
signature_private_key_file="spieler2.key"
authority_certificate_file="ca.crt"

```

The RPIs will run a dhcp-server on WiFI Interface:

RPI1: 192.168.0.0/24
RPI2: 192.168.10.0/24

Spieler1: LAN 192.168.1.0/24

PC1 connected with WLAN can ping 192.168.254.253
RPI1 can ping 192.168.254.2

Spieler1: LAN 192.168.2.0/24

PC2 connected with WLAN can **not ping** 192.168.254.253
RPI2 can ping 192.168.254.253

**Comment by richman1000000** [comment]
On server
[router]
relay_mode_enabled=yes

**Comment by ds2k5** [comment]
Thanks, but did not work.

```
[fscp]
listen_on=0.0.0.0:12000
cipher_capability=aes256-gcm

[tap_adapter]
ipv4_address_prefix_length=192.168.254.253/24

[security]
signature_certificate_file="spieler1.crt"
signature_private_key_file="spieler1.key"
authority_certificate_file="ca.crt"

[router]
relay_mode_enabled=yes
```

**Comment by richman1000000** [comment]
can you post a picture-diagram with networks? I looks like you have 5 networks and you need to do proper routing

**Comment by ds2k5** [comment]
```


              Spieler1 VPN: 192.168.254.253                   Spieler2 192.168.254.2

PC1 192.168.10.10 <---> RPI1 WiFI 192.168.10.0/24  
                        RPI1 LAN 192.168.1.254  
                          R1 LAN 192.168.1.0/24 
                                R1 WAN 172.16.1.1  <--------->   R2 WAN 172.16.1.2
                                                                    R2 LAN 192.168.2.0/24 <--->  RPI2 (LAN 192.168.2.254)  
                                                                          RPI2 WiFi 192.168.20.0/24   <--->  PC2 192.168.20.10



```

**Comment by richman1000000** [comment]
wow!.
You need to write proper routes on each of you gateways

**Comment by s-vincent** [comment]
@ds2k5 Did answer from @richman1000000 helped on your setup issue ?

**Comment by ds2k5** [comment]
Did net get it to work.

**Comment by richman1000000** [comment]
@ds2k5  are you using NAT anywhere in your setup?
we can check it step by step.
1. can you ping 192.168.10.10 and  192.168.1.254   back and forth?

**Comment by s-vincent** [comment]
No reply since last year, closing. Feel free to reopen if progress has been made.
