### ISSUE TITLE
build new release

### ISSUE THREAD

**Issue by richman1000000** [freelan-developers/freelan#190]
can you build new release like https://github.com/freelan-developers/freelan/releases for windows10x64 with fixed #74 ?

**Comment by s-vincent** [comment]
For now we have not a release yet.

@richman1000000 For the moment you can take the artifact built by appveyor on master branch : https://ci.appveyor.com/project/ereOn/azmq/build/job/3fxkduebpi0vuioh/artifacts

@ereOn any news / updates to make a new release ?

**Comment by richman1000000** [comment]
maybe you can just do HotFix releases then? Just for Major bugs fixed.

PS. I've downloaded artifact build, thank you. Cause windows compilation is complicated thing...

**Comment by PalmaNicola** [comment]
Is there any roadmap for any new release?

**Comment by ereOn** [comment]
I should be releasing soon but i am currently working 70+ hours/week which makes my free time an unavailable luxury these days. Hopefully i'll manage to get some free time in the upcoming weeks. Sorry for the delay. Le 15 mars 2019 10 h 23, Nicola Palma <notifications@github.com> a écrit :Is there any roadmap for any new release?

**Comment by s-vincent** [comment]
After offline talk with @ereOn, I will work on the release the 2.2 version. I expect to have something at the end of next week.

**Comment by s-vincent** [comment]
Release 2.2 is out : https://github.com/freelan-developers/freelan/releases/tag/2.2.
