### ISSUE TITLE
Freelan fails to install on macOS Mojave

### ISSUE THREAD

**Issue by stochastic-thread** [freelan-developers/freelan#191]
![image](https://user-images.githubusercontent.com/8550019/55677155-c1c65600-58b0-11e9-9424-3dd697517dfb.png)

I downloaded the .pkg and allowed the install in my System Preferences, since its from an "unidentified developer," but then it failed unexpectedly. 

Is this a known issue?

I am using macOS Mojave 10.14.3

**Comment by stochastic-thread** [comment]
If you tell me where to look for logs I'd be happy to add them to this issue, but I'm just not sure where to look.

**Comment by sm0g** [comment]
I had a similar issue with High Sierra. I was able to install it again after that I unblocked it in security settings.

**Comment by stochastic-thread** [comment]
I unblocked it too, but it still fails after doing that unblocking. I install a lot of developer libraries that require me to do that same step of unblocking before actually running the installation (.dmg/.pkg) but it still persists. Is there a place where I can check for install logs to get a better sense of why its failing?

**Comment by sm0g** [comment]
Maybe you'll find something within [Mac Console app](https://www.howtogeek.com/wp-content/uploads/2018/06/ximg_5b2d7076a5021.png.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.1lryLYFTQs.png).

**Comment by zachbellay** [comment]
If you go to Settings>Security & Privacy>General, at the bottom it will say that an application was blocked from installing, hit "Allow" and this problem is solved.
