### ISSUE TITLE
Contact ipv4 and ipv6 hosts. Is it possible?

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [freelan-developers/freelan#196]
Currently it does not seem to be possible to contact both IPv6 and IPv4 servers

if `hostname_resolution_protocol` is set to `ipv6` then `freelan` seems to treat ipv4 address as hostnames that need to be resolved.

```
hostname_resolution_protocol=ipv6
contact=1.2.3.4:12000
contact=[2aa1::1]:12000
```

Then the debug log is as follows:
```
[DEBUG] Unable to send HELLO to 1.2.3.4:12000: Host not found (authoritative)
```

Or if if `hostname_resolution_protocol` is set to `ipv4` then `freelan` seems to treat ipv6 address as hostnames that need to be resolved.

```
hostname_resolution_protocol=ipv4
contact=1.2.3.4:12000
contact=[2aa1::1]:12000
```

Then the debug log is as follows:
```
[DEBUG] Unable to send HELLO to 2aa1::1: Host not found (authoritative)
```

Is this intentional? Is it possible to contact an ipv4 and an ipv6 host? Can the feature be added if not currently possible?

This is on a macos with version 2.2

**Comment by QuantumEntangledAndy** [comment]
Ok so it seems that contacting both is possible but that in the current state it is not working. I have a working build that allows you to contact both v4 and v6 on a mac but I am going to test it on a linux before I create the pull request.

**Comment by s-vincent** [comment]
It should be good with revision fd5e650eb355d4c9595cef4879a4c575e71c9da5.
