### ISSUE TITLE
Nasty bug with hostname verification in --fscp.contact

### ISSUE THREAD

**Issue by NightSkyAsHate** [freelan-developers/freelan#201]
Any DNS address starts with a digit causes an error:
[ERROR] the argument ('4chan.org:12000') for option '--fscp.contact' is invalid

![1](https://user-images.githubusercontent.com/44664331/65798207-b7a75500-e179-11e9-88ac-353d1e2b64cd.png)
![2](https://user-images.githubusercontent.com/44664331/65798034-5b443580-e179-11e9-9a15-41a13a4a1e54.png)

**Comment by richman1000000** [comment]
interesting.
I believe this is windows specific. Bug don't appear on linux server

![image](https://user-images.githubusercontent.com/9943374/65799725-7fa21100-e17d-11e9-987e-c373b01e08be.png)

**Comment by s-vincent** [comment]
That was a tricky thing. In facts there was parsing issues : 
- all numeric domain/subdomain ;
- domain/subdomain beginning with a digit. 

For the record, on GNU/Linux, "4" is a valid address (try "ping 4") but on Windows it fails.

Fixes has been done in revision 4bfe5a7be1a26b04c43fc4d9768cb5238bceee0c.

**Comment by s-vincent** [comment]
And for the record also, a (all) numeric subdomain or domain is perfectly valid according to RFC1123.
