### ISSUE TITLE
If I have no any public IP or hostname but only 2 subnet IPs within different routers?

### ISSUE THREAD

**Issue by saltyzero** [freelan-developers/freelan#202]
In this case, can I connect them by freelan? I have these 2 routers public IPs and I can't do port mapping on it.

**Comment by s-vincent** [comment]
Hi,

If your routers can do UPnP it may be possible.

**Comment by saltyzero** [comment]
> Hi,
> 
> If your routers can do UPnP it may be possible.

Yes, of course. Can I find one config template for this?

**Comment by s-vincent** [comment]
You have to set '''upnp_enabled=yes''' in [fscp] section of the configuration file.

The mapped port should be 12000 on the public IP side.

**Comment by saltyzero** [comment]
> You have to set '''upnp_enabled=yes''' in [fscp] section of the configuration file.
> 
> The mapped port should be 12000 on the public IP side.

It works. lol
