### ISSUE TITLE
"UPnP to traverse NAT enabled" missing in Release Notes 2.2

### ISSUE THREAD

**Issue by HenryNe** [freelan-developers/freelan#212]
On update from revision 2.0 to revision 2.2 a new feature "upnp_enabled=yes" is enabled by default, related to PP #144.
I missing this in Release Notes:

> Enable UPnP to traverse NAT

**Comment by s-vincent** [comment]
Hi,

Thanks, I updated release 2.2 page (https://github.com/freelan-developers/freelan/releases/tag/2.2).
