### ISSUE TITLE
freelan on vServer where /dev/net/tap is missing

### ISSUE THREAD

**Issue by HenryNe** [freelan-developers/freelan#218]
Freelan stops running on a vServer, because can not create node /dev/net/tap:
```
2020-03-22T12:34:29.601102 [INFORMATION] FSCP server started.
2020-03-22T12:34:29.601682 [ERROR] Operation not permitted
```
The detail was found with strace:
```
# freelan -f -d -c /etc/freelan/freelan.conf
...
access("/dev/net/tap", F_OK)            = -1 ENOENT (No such file or directory)
mknod("/dev/net/tap", S_IFCHR|0600, makedev(10, 200)) = -1 EPERM (Operation not permitted)
```
Workaround: Create a soft link from existing /dev/net/tun:
```
# ln -s tun /dev/net/tap
# ls -la /dev/net/
total 0
drwxr-xr-x 2 root   root         80 Mar 22 12:55 .
drwxr-xr-x 8 root   root        500 Mar 22 12:42 ..
lrwxrwxrwx 1 root   root          3 Mar 22 12:55 tap -> tun
crw-rw-rw- 1 nobody nogroup 10, 200 Mar 22 10:24 tun
```

The documentation about devices says, use it for TUN and TAP. There not exist a separate device name for TAP.
https://www.kernel.org/doc/html/v4.15/admin-guide/devices.html:

> 200 = /dev/net/tun      TAP/TUN network device

Why not open `/dev/net/tun` in all cases, for tun and tap? OpenVPN and others does not differ for the mode.

**Comment by s-vincent** [comment]
Hi and thanks for report and PR !

For choosing /dev/net/tap instead of /dev/net/tun, well I guess I do not remember.
@ereOn I ask for your memory :).

Maybe there was a distinction in old GNU/Linux kernel ?

Anyway I will review your PR ASAP. Thanks again for that !

**Comment by ereOn** [comment]
So, what I remember is that when we first started FreeLAN (was that already +10 years ago ?!), `tun` and `tap` were highly distinct choices. `tun` did not allow real-LAN emulation (we wanted to have control over the lower layers of the encapsulated trafic, including ARP for instance) so the default choice has always been `tap` for that reason.

Long story short, I see no valid reason today to prefer `tap` over `tun`, especially as `tun` is a sensible choice in most cases. It may just have been a bad choice to begin with (hell, we hadn't even graduated at the time :P). Especially as Henry mentions, it causes permission issues on some platforms.

Feel free to change it if it makes more sense. And thanks for the info! Much appreciated.

**Comment by HenryNe** [comment]
Yes in older kernel it was `/dev/tap0`, and separate name for every node index.
https://www.kernel.org/doc/html/v4.15/admin-guide/devices.html:
>                  16 = /dev/tap0         First Ethertap device
>                     ...
>                  31 = /dev/tap15        16th Ethertap device

**Comment by s-vincent** [comment]
PR #219 merged. Thanks !
