### ISSUE TITLE
Request: debian buster package

### ISSUE THREAD

**Issue by matthayter** [freelan-developers/freelan#222]
Hi team - looks like there's [no official packge](https://packages.debian.org/search?searchon=names&keywords=freelan) for the stable Debian Buster at the moment, but there is for Bullseye (testing). I'm installing from source (nice guide, thanks for that!) but I thought it might be nice to have an official package too.

I'd make an official backport myself, but it'd be new to me and I figure it's probably easier to add to the build process anyway (unless I'm just not aware of some reason it doesn't already exist).

Thanks and keep up the wonderful work!

**Comment by s-vincent** [comment]
Official Debian package source is at https://salsa.debian.org/debian/freelan.
