### ISSUE TITLE
Remove from windows

### ISSUE THREAD

**Issue by fmammadov85** [freelan-developers/freelan#227]
Hello I want to remove freelan from windows 10.So I camed to C/Programfiles/Freelan and unistalled it and then after restart  I login from control panel to services i cant find freelan service but my computer already connected to this service vpn, Thyen i writed what is my ip in the google then sawed that my ip is changed, I am also checked delete with revo uninstaller but it didnt give result to me, how can i delete it from win10 please help me.

**Comment by s-vincent** [comment]
Do you try Windows's "Apps and features" ?
=> https://www.businessinsider.fr/us/how-to-uninstall-programs-on-windows-10

Maybe a reboot after, just to be sure.

**Comment by fmammadov85** [comment]
Okay thank you very much, I checked it and i succesfully deleted it, Thanks
