### ISSUE TITLE
Split Tunnel Setup?

### ISSUE THREAD

**Issue by ndo360** [freelan-developers/freelan#228]
Greetings!

I was wondering if there was a way to configure a split tunnel setup within FreeLAN. Mainly so that only traffic destined for the network would go through the VPN, while everything else would go through the user's own internet connection.

Anyone know how to configure this?

**Comment by richman1000000** [comment]
it is split tunneled in 1st place actually

**Comment by ndo360** [comment]
Ah this is amazing news! I actually suspected this after noticing my Public IP doesn't change when connected.

I just wanted to be sure and verify this, thanks for the reply!
