### ISSUE TITLE
IS this a Virus?

### ISSUE THREAD

**Issue by EmanuelPlays** [freelan-developers/freelan#249]
**Windows has reported it as virus**

**Comment by Vasdranna** [comment]
Well, 2/72 security vendors flagged this file as malicious according to Virus Total. Also the download links in the site doesn't work, they redirect to another strange website. 

I know it could be a false positive due to the nature of the software, but I remain doubtful.

**Comment by richman1000000** [comment]
FreeLan installs driver into system.
If your are certified developer you need to have dedicated site not posting drivers on github.

That is why this behavior considered bad for regular software by Antiviruses.

**Comment by ereOn** [comment]
Freelan is **NOT** a virus but you shouldn't take my word for it (or anyone else's really).

I have not been maintaining this project for the last years so it's no surprise this wasn't flagged sooner. The process for providing/installing drivers in Windows certainly has improved in terms of security, and I don't want to pay to be certified or anything like it when I don't intend to support/maintain the project actively anymore.
