### ISSUE TITLE
error LNK1104: cannot open file 'libboost_date_time.lib' in vs2013 after compiling freelan project 

### ISSUE THREAD

**Issue by abolfazlsj** [freelan-developers/freelan#31]
Hello I am using boost_1_55_0 for freelan I could compile all the projects on vs2013 except freelan project. and I saw error below :

error LNK1104: cannot open file 'libboost_date_time.lib' freelan

when I compiled boost libraries I get some libs with some names like below :

libboost_date_time-vc120-mt-1_55.lib
libboost_date_time-vc120-mt-gd-1_55.lib

as you see there is no 'libboost_date_time.lib' how can I find that.

**Comment by magmine** [comment]
I've did what @abolfazlsj said, and then rebuilt using:
> b2 -a -j8 --address-model=64

where:
-a to rebuild all
-j8 to use 8 cores in compilation
--address-model=64 for 64-bit
