### ISSUE TITLE
Support using preconfigured tuntap devices

### ISSUE THREAD

**Issue by wrouesnel** [freelan-developers/freelan#36]
On Linux it's not possible for a regular user to create a tuntap device, or configure it in anyway (bring it up/down, set the IP address etc.) but freelan uses the user's home directory to perform operations and store configuration.

It would be good to break out the code which opens tuntap devices from the code which configures them, so the latter could be added as a binary/daemon which runs as setuid root, allowing the main freelan2 executable to then be run by ordinary user accounts.

A first step would simply be detecting and handling the case of running without root but with an accessible tuntap device appropriately.

In a Hamachi-like use-case, a single tuntap device would be more then enough - Hamachi firewalled network segments from each other but used the same address range.

**Comment by s-vincent** [comment]
It is possible to reuse an existing tun/tap interface with a little modifications in asiotap library if we pass an interface name:
 * do not try to create /dev/net/tun or /dev/net/tap in posix_tap_adapter::open() method;
 * do not failed if SIOCSIFTXQLEN ioctl() does not succeed;
 * do not failed if posix_tap_adapter::configure() failed.

And if the following is set on the system:
 * an tun/tap is created using user/group attribute (ip tuntap add tap4 mode tap user seb group seb)
 * /dev/net/tap and/or /dev/net/tun has read-write permission for the user;
 * IPv4/IPv6 addresses and/or automatic configuration is already done on the interface.

On the UI side, we can reuse the [fscp].name option and change its logic: if it set on Linux, it requires an existing tun/tap interface. So if posix_tap_adapter::_name is empty(), we avoid setting system_error and logs something instead.

I don't think it is a too long to implement. I will do something today if I find some time.

WDYT ?

**Comment by s-vincent** [comment]
@wrouesnel You can check the [tun branch](https://github.com/s-vincent/freelan/tree/tun) if it fits to your needs.

@ereOn if you agree with the proposed solution, I can do a PR with this branch.

**Comment by s-vincent** [comment]
@wrouesnel You can check the [tun branch](https://github.com/s-vincent/freelan/tree/tun) if it fits to your needs.

@ereOn if you agree with the proposed solution, I can do a PR with this branch.

**Comment by ereOn** [comment]
@s-vincent Seems sane to me !

**Comment by s-vincent** [comment]
@wrouesnel @ereOn Please see, test and review PR #153.

**Comment by s-vincent** [comment]
PR #153 has been merged.
