### ISSUE TITLE
Easy speed create lan

### ISSUE THREAD

**Issue by fcore117** [freelan-developers/freelan#42]
Please add fast way to create direct LAN without messing with horrible certs, i would like to get rid of Evolve or Hamachi and use Freelan for LAN connectivity.

**Comment by fcore117** [comment]
it is really good to see that active development goes on, keep up really good work. Now i wait when i can finally uninstall Hamachi & Evolve horror and install Freelan.

**Comment by fcore117** [comment]
Now i tried OpenVPN to create LAN but no success and ultra hard config and certificate fuzz. Just left from Evolve VPN because i got messages daily basis that servers are overloaded. Tried Hamachi but their forced IP addresses are out of my needed range.

How this HTTP mechanism works? do i just enter friends IP and usernama and password and LAN is created?

**Comment by ereOn** [comment]
@fcore117 At least one host still has to create a certificate authority (the one hosting the server) and makes sure his public IP address is reachable by the others. Then the others can just connect using an username and a password.

Having a 100% certificate-less solution is unlikely and would provide poor security. As much as I intend to make FreeLAN's configuration as easy as possible, I won't sacrifice security for this. I guess I could provide a mode that fixes sessions keys (you would only have to provide a shared secret password). I'll have to think about it though, as it's far from being trivial/riskless.
