### ISSUE TITLE
DHCP proxy should respond to ARP like a real device

### ISSUE THREAD

**Issue by White-Tiger** [freelan-developers/freelan#46]
The DHCP proxy does currently not reply to ARP requests, this also troubles Windows higher than XP as their screwed up networking requires a default gateway to be set on ones network to identify it and allowing traffic across it.

**Comment by ereOn** [comment]
@White-Tiger Can you describe exactly how you'd want FreeLAN to behave in that regard and what is the problem you'd like to solve ?

It is unclear to me what exactly constitutes a problem as FreeLAN usually operates well even on Windows. Do you have some particular networking setup that causes problems ?

**Comment by White-Tiger** [comment]
this issue got created because I've been asked to do so in a different communication. (mailing list)

Windows requires a default gateway that answers to ARP requests to identify a network. An identified network is important to be able to save settings, as well as to configure it as "public", "private" or "work". Otherwise Windows' firewall blocks most traffic.

The answer I've got (from you) on the mailing list was this:
> When you say "gateway" do you actually mean "DHCP server" ? Because it's not the same thing (in most cases the same device does both but it doesn't have to be that way).
>
> That being said, it makes sense for the virtual DHCP server to reply to ARP requests the same way a real host would. Could you please add a ticket for this feature (https://github.com/freelan-developers/freelan-all/issues) ? ”

Otherwise.. my targeted setup was quite like the hybrid one as seen on the webpage
![hybrid schematic](http://freelan.org/static/images/hybrid.png)

Was meant to be like this:
![hybrid schematic with WWW access](https://cloud.githubusercontent.com/assets/1467733/9049651/9686e182-3a44-11e5-9af6-42942d276489.png)

**Comment by ereOn** [comment]
@White-Tiger I recall now. Sorry, for not doing so earlier, I'm kinda swamped with tasks these days.

Thank you for the additional information as well as the graphics. I'll see how that can be implemented.

**Comment by s-vincent** [comment]
@ereOn Any news on that ?

If I understand correctly, if DHCP proxy is enabled, we should just answer to all ARP request "the ethernet address corresponding to IP you ask is my ethernet address" ? Right ?

**Comment by ereOn** [comment]
@s-vincent I'm not sure.

What you describes seems more like enabling the ARP proxy, for which the configuration states:

> 
> # Whether to enable the ARP proxy.
> #
> # When the ARP proxy is enabled, all ARP requests are silently rerouted to an
> # internal ARP server that always replies positively. Remote hosts never
> # receive any ARP request.
> #
> # Warning: Setting this parameter can lead to connectivity issues. It is
> # provided solely for debugging and testing purposes.
> #
> # Default: no
> #arp_proxy_enabled=no

If I recall correctly, the DHCP proxy sends back its requests from the network address (so if we are in `192.168.4.0/24`, it will use `192.168.4.0` to reply - as weird as it might seem). Since this should not be a valid IP address for that range I think I never bothered to reply to ARP requests for it. But apparently, new Windows allow sending ARP requests even to this address (?!) so it might make sense to actually reply to those.

Does it make sense ?

P.S: It's been way too long since I put my head in that code. I could be completely off the mark - please don't take any of my recollections for an absolute authoritative truth.

**Comment by s-vincent** [comment]
Effectively on Windows, it need a valid network gateway to be considered as an "identified network" but in case of FreeLAN we just connect to a network (i.e. 9.0.0.0/24) and no gateway is specified. We just want to connect with other peers. It is is possible to specify a gateway either manually (with route command) or via configuration.

For the last one, if one peer (9.0.0.1) wants to acts as a gateway for other, it can specify router.local_ip_route=ipv4_proxy. With that settings, it will send the routes to others (0.0.0.0/0 via 9.0.0.1 for example). But as it is a system parameter other peers have to authorize it in the configuration (router.system_route_acceptance_policy=unicast_with_gateway or any_with_gateway). With that configuration network is considered as a identified network. Side note: be careful and read the configuration help as it can be a huge security risk to accept route from others. Better go to the manual way.

So all in all I think it has nothing to do with the DHCP proxy.

@White-Tiger In your example, do you try to add a route on 9.0.0.4 machine for 0.0.0.0/0 (gateway) via 9.0.0.200 ?

**Comment by s-vincent** [comment]
No answer for 1 month and I don't see any problems, I close the issue.

Feel free to reopen if any.
