### ISSUE TITLE
Too many contact= at config

### ISSUE THREAD

**Issue by Anime4000** [freelan-developers/freelan#75]
This might be silly question, as my current config, every time new client to enter, all other existing client had to edit and add `contact=` on config file, expecting home user has dynamic IP and some of my friend don't have DDNS.

I have server running, Iodine (VPN over DNS), Free LAN (P2P) and Dante SOCKS 5 Proxy *ehem... bittorrent, ehem bypass WiFi Login Protal using Iodine*

IF I ask my friend, remove all `contact=` except server, still P2P or become Client-Server-Client? *I hope Free LAN is like DHT or more like BitTorrent, using tracker to find client.*

**Comment by ereOn** [comment]
If you are using certificates for authentication and you specify `dynamic_contact` entries on the clients, FreeLAN will indeed behave as a tracker and share peers addresses to other peers.
