### ISSUE TITLE
Why is speed so slow in my setup ?

### ISSUE THREAD

**Issue by noanti** [freelan-developers/freelan#76]
I compiled freelan2.1 on my vps and connected it successfully,but speed is very slow.
When I access my  vps directly,download speed can reach 850kb/s.
But if I access vps via freelan(9.0.0.1),download speed only 90kb/s.

Debug info output lots of follow message:

> 2015-06-09T13:03:25.775810 [TRACE] Received a data message from xxx.xxx.242.224:13975 but its sequence number is outdated (received: 2556, expecting: 2557). Ignoring.

I config vps  following the Quick-start.

vps:

```
freelan --security.passphrase "my secret"
```

pc:

```
freelan --security.passphrase "my secret" --tap_adapter.ipv4_address_prefix_length 9.0.0.2/24 --fscp.contact xxx.xxx.xxx.xxx:12000
```

**Comment by noanti** [comment]
#asdsadas
*sdfsdf

**Comment by ereOn** [comment]
Are you using FreeLAN through a WIFI link ?

**Comment by noanti** [comment]
yes

**Comment by ereOn** [comment]
VPNs are particularly vulnerable from packet losses/reordering (which happen a lot more on WIFI links).

At this point, I'd suggest trying the following things before tweaking FreeLAN's configuration:
- Try to perform the same tests on a wired connection: the VPN speed should obviously still be lower than the direct speed (security and encapsulation come at a cost) but not 10x slower. On my last benchmark, FreeLAN's overhead was around 10%.
- If you can't perform a wired-test easily, try to temporarily disable all other devices using your Wifi network: the global Wifi bandwidth is shared between all the devices, so the more device there is, the more interruption and packet loss/reordering are likely to occur.

**Comment by noanti** [comment]
Download speed is decreasing on a wired connection...
On beginning,it can reach around 700kb/s.Finally speed is 100+kb/s
I have tested many times,it always like this.
![- 2015 06 10 - 02 22 12](https://cloud.githubusercontent.com/assets/6761874/8066012/baa4898c-0f17-11e5-8dfd-9dc475ddc561.png)
![- 2015 06 10 - 02 22 42](https://cloud.githubusercontent.com/assets/6761874/8066014/bfa029aa-0f17-11e5-9f9e-eb80f6d5c5e3.png)

**Comment by ereOn** [comment]
At this point I would try playing with the `mtu` value (and the `mss_override`) to see if that changes anything. From what you describe, it seems that your TCP stack is too optimistic and starts the TCP transfer way faster than the underlying link can handle. I wouldn't trust the value given in the first seconds of the download.

Can you use a tool like [`iperf` ](https://iperf.fr/) and perform a UDP test first to see if the problems lies with TCP or something else ?

**Comment by noanti** [comment]
If I have 2 nodes behind NAT,and I don't have permission to config port forwarding.Can I connect them with a public server just like how n2n works?

**Comment by ereOn** [comment]
Yes. FreeLAN can adapt to any network topology. In this case you'd have to host a FreeLAN host that acts as a `relay` (it doesn't need to have a tap adapter).

Check the configuration file comments for details about those options.

**Comment by noanti** [comment]
Do the two node communicate with each other directly or all traffic will go through relay host?

**Comment by ereOn** [comment]
If you want the nodes to communicate directly, you will need to make sure your NAT routers aren't symmetric and/or to open the ports to do so. This is no specific to FreeLAN : any other peer-to-peer software will have the same requirement.

The alternative is to have the host communicating through a relay in which case the connection will be indirect.

**Comment by noanti** [comment]
Thank you :)

**Comment by s-vincent** [comment]
Any news on this issue ? Still performance problems ?

**Comment by ereOn** [comment]
Fell free to reopen if you still have an issue/questions on this.
