### ISSUE TITLE
nitpicks about the 2.0 release

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan#77]
2.0.tar.gz isn't an optimal filename.  freelan-2.0.tar.gz would be better.

The build system looks around for a git directory.  The tarball release is not a VCS and an error message is displayed.  No further problems during the build.

**Comment by leggewie** [comment]
A much more serious problem is that the tarball is not identical to the 2.0 tag.  There is a diff in the file packaging/windows/files/README.txt

**Comment by ereOn** [comment]
@leggewie That is weird. The archive is generated by Github, from the tag. I don't understand how that can differ. Could you please copy-paste the diff so I can have a look ?

Regarding the name, I sadly can't change it as it is Github that dictates this.

**Comment by leggewie** [comment]
The diff was indeed a local diff I hadn't yet push because it was so minor.  I did now and created pull request #78.
As regards filenames, I do not know how github wants people to handle this, but maybe freelan/2.0 or freelan-2.0 is the better tag?
Were you able to confirm the complaint during the build about the missing git information?

**Comment by s-vincent** [comment]
Github uses the tag name to generate the archive file. It is apparently not possible to use a specific name before the tag version (see https://stackoverflow.com/a/40835009). A possible way (not tested) could be to tag a version with the archive name we want (i.e. freelan-2.1 instead of 2.1).

@leggewie Can you remind me what is the build system issue you mentionned ? Is it related to the fact that packaging/debian points to freelan-debian.git (git submodule) ?

**Comment by leggewie** [comment]
Here are the steps to reproduce the error

````
$ wget https://github.com/freelan-developers/freelan/archive/2.0.tar.gz
$ tar xf 2.0.tar.gz
$ cd freelan-2.0/
$ make clean
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make: *** No rule to make target `clean'.  Stop.
````
At least that's the one I came up with now ;-)

**Comment by s-vincent** [comment]
The guilty line is `PRODUCT_VERSION:=$(shell git describe)` in the Makefile :(.

However it is no longer used in master repository since we now use a VERSION file.

I believe we can close this issue since it will not appear in future 2.1 release.

**Comment by leggewie** [comment]
Good to know.  Thanks.

Only thing remaining then is to decide on a tag format that will not result in 2.1.tar.gz.  What are other github projects using?  Those that use github to release tarballs.

**Comment by s-vincent** [comment]
I am affraid that the majority of github projects have releases like v1.x.y (docker-ce, ...). It is the way github works...

I also see that when the archive is uncompress it contains directory which are of the form project-name-archive (i.e. v2.0.tar.gz => myproject-v2.0). So the solution I proposed earlier (to tag with the project name and version) we will have something like freelan-freelan-v2.0 which is "strange" from my point of view.

**Comment by s-vincent** [comment]
@ereOn @leggewie So what your opinion for the future ?

Keeping tag name on the form 2.x and having 2.x.tar.gz/zip file (uncompressed as freelan-2.x directory) or having a tag named freelan-2.1and having freelan-2.x.tar.gz/zip (but uncompressed as freelan-freelan-2.x) ?

Personnaly I would rather vote for the first one (keep as it is now).

**Comment by leggewie** [comment]
I am sure there has to be a better way.  At the moment, I can't suggest one, though.

**Comment by leggewie** [comment]
One way, of course, even if not a good one is to specifically release the tarball alongside other binary files ([example](https://github.com/vbajpai/nfql/releases/tag/v0.7.1)). Just putting this out there as an option. Not endorsing this.

**Comment by leggewie** [comment]
Here is [what Debian has to say about making a release from github](https://wiki.debian.org/Creating%20signed%20GitHub%20releases).  Unfortunately, it's inconsistent.  It seems like nobody is too concerned about the ugly and less-than-helpful filenames for the tarballs.  But it seems like that's the way it is.

Closing the ticket. We have no way to get around that github limitation in a reasonable manner and it's not a dealbreaker.  I'll try to deal with it by mangling the filename in debian.

**Comment by leggewie** [comment]
JFTR, apparently github does "rename" the 2.0.tar.gz to freelan-2.0.tar.gz when downloading in the browser (I assume there is some JavaScript hack going on). Good for the browser, but it doesn't work for tools like wget.  Ugly is all I can say, but it's really a github issue they need to consider.
