### ISSUE TITLE
 compilation error on debian jessie amd64

### ISSUE THREAD

**Issue by richman1000000** [freelan-developers/freelan#79]
Hi!
I have this problem during compiling freelan 2.0
![untitled](https://cloud.githubusercontent.com/assets/9943374/8205022/b0a7172c-150e-11e5-9e79-bb401874e77b.png)

Does any one have this issue?
My version of gcc (Debian 4.9.2-10) 4.9.2

**Comment by leggewie** [comment]
Do you know how to work with dsc files?  If so, then get http://oss.leggewie.org/wip/freelan/freelan_2.0-0rl1.dsc and compile that.  It compiles fine here.

**Comment by richman1000000** [comment]
Now, I don't. But I will learn now.
In your file dsc file there is a additional dependence  "python-argparse" which is not included in original BUILD.md. I installed that dependency and everything compiled fine.
Thank you

**Comment by ereOn** [comment]
@richman1000000 Is it safe to assume that your issue is resolved ?

If so, can we close it ?

**Comment by leggewie** [comment]
On 19.06.2015 14:32, richman1000000 wrote:
> In your file dsc file there is a additional dependence "python-argparse"
> which is not included in original BUILD.md. I installed that dependency
> and everything compiled fine.

I'm happy to hear things are working for you now.  But I can hardly
imagine that the python-argparse dependency is what fixed things for
you.  I added that to compile on lucid which by now has even reached
end-of-life after being released more than 5 years ago.  It still used
python 2.5.  python-argparse was incorporated into python in 2.7 IIRC.

In any case, good to hear compilation is working for you now.

**Comment by richman1000000** [comment]
Yes ,I think you can close it!

By the way I learned how to created dsc and deb file now.
I really thankful for your help!
