### ISSUE TITLE
Create build-machines

### ISSUE THREAD

**Issue by ereOn** [freelan-developers/freelan#8]
Creating build machine for each of the operating system would be nice.

http://buildbot.net/ seems like a good candidate for that.

**Comment by chrisidefix** [comment]
I noticed you have a travis config included already. Travis supports linux and os x (possibly Windows in the far-far-away future), but I guess for now the config could be extended to os x

**Comment by ereOn** [comment]
@chrisidefix Indeed. If you have some experience with it, feel free to submit a PR with the necessary changes !

**Comment by s-vincent** [comment]
A tentative to add macOS build to travis is done in PR #140.

**Comment by s-vincent** [comment]
For Windows, we can use [AppVeyor](https://www.appveyor.com). It is free for open source projects and it can also be integrated in github like Travis CI (see https://github.com/marketplace/appveyor).

@ereOn WDYT ?

**Comment by ereOn** [comment]
@s-vincent I already tried AppVeyor a while back but didn't come up with a satisfying setup. It was a while back though so things have likely changed for the better on that front.

I'd be obviously more than willing to consider it if you want to give this another go !

**Comment by s-vincent** [comment]
@ereOn I am currently on it :). But I have to push first some changes to build with VS 2017.

Can you can install AppVeyor github app for freelan repository ?

**Comment by s-vincent** [comment]
I have written an appveyor file [here](https://github.com/s-vincent/freelan/blob/appveyor/.appveyor.yml). I have not tested it yet. When the AppVeyor app will be configured I will do a PR to trigger a build and fix the yml if necessary.

**Comment by ereOn** [comment]
@s-vincent It seems it's setup already. From my previous try perhaps ?

**Comment by s-vincent** [comment]
Well at least it does not seems to react to PR build. Maybe check the configuration (I have no access by myself), see http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests#comment_33212404.

**Comment by ereOn** [comment]
The "pull request" tickbox is already checked.

Perhaps the webhook URL is wrong ? Can you tell me which webhook URL Appveyor gave you ?

**Comment by s-vincent** [comment]
I don't know which URL use. Maybe uninstall the appveyor app from repository and reinstall it would be good ?

**Comment by ereOn** [comment]
I relogged and added back permissions. I also removed my previous freelan project.

Can you give it another try ?

**Comment by s-vincent** [comment]
I adds a new PR #149 with appveyor.yml file but still does not seems to trigger build :(.

**Comment by ereOn** [comment]
@s-vincent They apparently don't have organization support... this sucks. I've manually added a project that seems to be able to fetch sources and start a build. It just doesn't work until your branch gets merged.

**Comment by s-vincent** [comment]
After some changes we have arrived to something with appveyor. At the moment first builds are baking for x64-Release (already passed success), x64-Debug, x86-Release and x86-Debug.

**Comment by s-vincent** [comment]
Build success for the four targets :).

**Comment by leggewie** [comment]
Congratulations.

This is new to me, where can I read how this stuff works?

**Comment by s-vincent** [comment]
For Travis CI (Linux/macOS builds): https://docs.travis-ci.com/user/getting-started
For Appveyor (Windows builds): https://www.appveyor.com/docs/

Both projects are similar, basically you provide a kind of [Ansible](https://docs.chef.io/)/[Chef](https://docs.chef.io/) provisioning files (in .travis.yml and appveyor.yml) and for each push/PR it will trigger a new build.

**Comment by s-vincent** [comment]
You can follow the build history for Travis CI here: https://travis-ci.org/freelan-developers/freelan/builds

**Comment by bchavez** [comment]
Does anyone have the **AppVeyor** build artifact link? Starting to get an itch to attempt to upgrade **Freelan** from `1.1` to `2.1`. Thanks!

**Comment by s-vincent** [comment]
Here it is https://ci.appveyor.com/project/ereOn/azmq/history.

By the way, as you want to build on Windows, let's try the vcpkg branch (also automated build via appveyor).

**Comment by bchavez** [comment]
@s-vincent , do you have a link to the freelan organization's build artifacts / project location on AppVeyor?

There was a commit e35aafb9c2935ed8e8a09274863b28bf39206b4b that might have indicated that a freelan organization was setup to replace `ereOn/azmq`. If not, I'll grab latest builds from `azmq`. Thanks.

**Comment by s-vincent** [comment]
The link has not changed but it is visible now on the commit page with travisCI ones.
