### ISSUE TITLE
freelan lacks a man-page

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan#81]
freelan lacks a man-page.  Do you want to maintain it as a separate file or rather auto-generate it after compilation, for example with help2man?

**Comment by ereOn** [comment]
I actually tried `help2man` and the result was very nice. I almost had nothing to change (thanks to Boost Program Options which generates a standard help string).

Is it possible to auto-generate the man pages as part of the package build ?

**Comment by leggewie** [comment]
On 20.06.2015 21:34, Julien Kauffmann wrote:
> Is it possible to auto-generate the man pages as part of the package build ?

I was thinking the same.

Should be simple

1) test for existance of help2man binary
2) call help2man binary and redirect output to freelan.1

That should really be it

**Comment by ereOn** [comment]
Closing this since we agreed on a solution. Feel free to reopen in any case.

**Comment by leggewie** [comment]
let's close this when we have integrated building the manpage into the build process (see my previous comment). OK?

**Comment by ereOn** [comment]
No problem.

**Comment by s-vincent** [comment]
@leggewie @ereOn Please see, test and review PR #157.

**Comment by s-vincent** [comment]
PR #157 has been merged. I close the issue.

Feel free to reopen if you have problems.
