### ISSUE TITLE
Update of deb package

### ISSUE THREAD

**Issue by show0k** [freelan-developers/freelan#87]
Hi,
I just tried to install freelan on a Debian base GNU/Linux distribution, and I seen that [deb package](http://debian.freelan.org/) is 2 years old, and I failed to add your pgp public key in the trusted dependencies...
I would be far easier to provide a standalone deb package or a binary compiled with statical links of all dependencies. As you use travis-ci to test you code, you could also use it to package your project for linux.
Thanks

**Comment by ereOn** [comment]
Hi,

Yes the current Debian repository was not maintained in a while and the 
new version 2.0 was not advertised yet. There is an ongoing request for 
having freelan 2.0 packages listed in the official Debian repositories 
but this takes time and we don't have any ETA on the request.

I can't commit on delivering anything on the side, as I simply don't 
have enough time. In the meanwhile, if you are knowledgable about 
packaging, it shouldn't be too hard to create the package yourself (or 
to just build from sources : that's super easy) should you need it. 
There is even some preliminary work in the official repository to get 
you started.

Cheers,

Julien.

**Comment by show0k** [comment]
I managed to make it work, but I wrote the issue because the compilation instructions are not so well documented so a GNU/Linux user who has no dev practice can't easy make it.
If I work again with it I'll try to wrote a pull request  for making the install more quick and play for Linux users.
Good luck with this project,
Cheers,
Théo
