### ISSUE TITLE
Read failed on freelan0. Error: End of file

### ISSUE THREAD

**Issue by wrouesnel** [freelan-developers/freelan#89]
```
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597204 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597209 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597213 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597218 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597222 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597227 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597232 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597237 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597242 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597246 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597251 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597256 [ERROR] Read failed on freelan0. Error: End of file
Aug 20 21:33:19 xen freelan[21095]: 2015-08-20T21:33:18.597260 [ERROR] Read failed on freelan0. Error: End of file
```

Running the latest builds on Ubuntu Vivid, syslog fills up the with preceding message. This is on kernel `3.19.0-15-generic`.

The problem seems to be a regression in behavior for asynchronous reads in this kernel which breaks the boost async_io functions. freelan still works, but it will spam the logs with this message continuously while it's not sending data (and use a lot of CPU while doing so).

It seems to be related to this kernel bug: https://bugzilla.kernel.org/show_bug.cgi?id=96381
Possibly not a freelan problem, but it's an issue till the kernel is fixed or a workaround found.

**Comment by ereOn** [comment]
@wrouesnel At first glande it seems to me that the only possible place for a fix is in Boost Asio's codebase.

Here is the code in FreeLAN that reads data:

	template <typename MutableBufferSequence, typename ReadHandler>
	void async_read(const MutableBufferSequence& buffers, ReadHandler handler)
	{
		m_descriptor.async_read_some(buffers, handler);
	}

As you can see, I used `async_read_some` which has a different behavior with the kernel issue. The result handler is called immediately and I have no control over that.

Have you asked the Boost mailing-list to see if they figured out a fix for that issue already ?

**Comment by s-vincent** [comment]
Any news on this issue ? Still problems with recent kernel or Boost version ?

**Comment by ereOn** [comment]
Let's close this for now. Feel free to reopen if there is relevant news on that topic.
