### ISSUE TITLE
Raspbian port - Raspberry Pi Support

### ISSUE THREAD

**Issue by tfft** [freelan-developers/freelan#90]
Hi, its great that you guys make the .deb packages available (http://debian.freelan.org) - would it be possible to,

 1. Include a Raspberry Pi (RPi) port - Raspbian distro - ARMv6/ARMv7 - Debian armhf based
 2. Your repo is rather dated (circa 2013), "jesse" (version 8) has already been released

Thanks.

**Comment by leggewie** [comment]
We've only very recently gotten freelan into Debian proper.

Would https://packages.debian.org/sid/armhf/freelan/download address your issue?  I'm away from my RPi for about a good week.  I might consider providing Raspbian packages if necessary, I'll probably use them myself.

**Comment by leggewie** [comment]
I kind of figured that mixing packages from Raspbian and Debian is not a good idea and indeed it isn't. https://www.raspbian.org/RaspbianFAQ#Can_I_mix_packages_from_the_Debian_repositories_with_Raspbian.3F

For the next few days at least your best option is to dget http://http.debian.net/debian/pool/main/f/freelan/freelan_2.0-1.dsc and compile yourself.

**Comment by snizzleorg** [comment]
anyone got it running on the raspberry pi?

**Comment by ereOn** [comment]
Yep. I did. It only depends on your operating system.
Le 15 juil. 2016 6:48 AM, snizzleorg <notifications@github.com> a écrit :anyone got it running on the raspberry pi?

**Comment by leggewie** [comment]
On 15.07.2016 20:17, Julien Kauffmann wrote:
> Yep. I did. It only depends on your operating system.

Did you compile the source straight away or use the Debian packaging to
compile?

**Comment by ereOn** [comment]
@leggewie It was a while back. Long before the official Debian packaging so I compiled from sources.

Anyway, FreeLAN should work and compile on every platform OpenVPN does as they use the same underlying principles/low-level APIs.

**Comment by leggewie** [comment]
I've now published an RPi binary at http://oss.leggewie.org/freelan/

@ereOn Feel free to add a pointer from the web page.

**Comment by ereOn** [comment]
@leggewie I finally updated the website. Thank you so much for handling this and providing the packages !

I wanted to add a special thanks on the website, but I figured I'd ask you first if you want to be mentioned.

**Comment by leggewie** [comment]
Sure, I love to read my name in famous places ;) Besides, it's in the domain name, anyhow ;-)

**Comment by leggewie** [comment]
https://github.com/freelan-developers/website/pull/4

**Comment by bernardoaraujor** [comment]
http://oss.leggewie.org/freelan/ is down :(

**Comment by leggewie** [comment]
@bernardoaraujor Sorry about that. The website is back up.
