### ISSUE TITLE
Getting server information from ... fails

### ISSUE THREAD

**Issue by aanno** [freelan-developers/freelan#91]
Using freelan from the wheezy-backport repository, I encounter the following

<pre>
# freelan -f -d -c /etc/freelan/freelan.conf
Reading configuration file at: "/etc/freelan/freelan.conf"
2015-09-15T10:49:13.264737 [DEBUG] Core opening on 0.0.0.0:12000...
2015-09-15T10:49:13.264920 [INFORMATION] Server mode enabled.
2015-09-15T10:49:13.265141 [INFORMATION] User agent set to "freelan/1.1".
2015-09-15T10:49:13.265327 [INFORMATION] Getting server information from ...
2015-09-15T10:49:13.265496 [DEBUG] Sent: GET https:///api/information
Error: Couldn't resolve host name
</pre>

freelan should work in server-mode here. Am I doing something silly?

**Comment by ereOn** [comment]
Can you give details about your configuration ?

If I had to guess, I'd say your `client.server_endpoint` configuration is empty.

**Comment by aanno** [comment]
My conf within only minimal comments:
<pre>
[server]

enabled=yes
network=mynetwork

public_endpoint=0.0.0.0
public_endpoint=::
hostname_resolution_protocol=ipv4
listen_on=0.0.0.0:12000
hello_timeout=3000
accept_contact_requests=yes
accept_contacts=yes
cipher_capability=aes256-gcm

[tap_adapter]

enabled=yes
ipv4_address_prefix_length=9.0.0.1/24
ipv6_address_prefix_length=2aa1::1/8
arp_proxy_enabled=no
arp_proxy_fake_ethernet_address=00:aa:bb:cc:dd:ee
dhcp_proxy_enabled=yes
dhcp_server_ipv4_address_prefix_length=9.0.0.0/24
dhcp_server_ipv6_address_prefix_length=2aa1::/8

[switch]

routing_method=switch
relay_mode_enabled=yes

[security]

# Unless server.enabled is set to "yes", this parameter is mandatory.
#signature_certificate_file=

# Unless server.enabled is set to "yes", this parameter is mandatory.
#signature_private_key_file=

encryption_certificate_file=/etc/freelan-server/server.crt
encryption_private_key_file=/etc/freelan-server/server.key

certificate_validation_method=default

authority_certificate_file=/etc/freelan/ca.crt

certificate_revocation_validation_method=none
</pre>

I didn't change much irt the default configuration...

**Comment by ereOn** [comment]
Something is off with the configuration you posted. It must differ somehow from the one you used for your first test as the lines:

    2015-09-15T10:49:13.265327 [INFORMATION] Getting server information from ...
    2015-09-15T10:49:13.265496 [DEBUG] Sent: GET https:///api/information

Indicate that the `client` feature was enabled, which is not the case in your configuration.

Also, specify `signature_certificate_file` and `signature_private_key_file` but leave `encryption_certificate_file` and `encryption_private_key_file` empty as the signature certificates will also be used for encryption if none are specified.

Please note that you need not specify `encryption_certificate_file`, `encryption_private_key_file` or even `authority_certificate_file` when in client/server mode anyway.

**Comment by aanno** [comment]
Hhm, when I use the configuration as I posted it:
<pre>
# freelan -f -d -c freelan-test.conf 
Reading configuration file at: "/root/freelan-test.conf"
2015-09-17T18:51:47.754268 [DEBUG] Core opening on 0.0.0.0:12000...
2015-09-17T18:51:47.754525 [INFORMATION] Server mode enabled.
2015-09-17T18:51:47.754805 [INFORMATION] User agent set to "freelan/1.1".
2015-09-17T18:51:47.755064 [INFORMATION] Getting server information from ...
2015-09-17T18:51:47.755237 [DEBUG] Sent: GET https:///api/information
Error: Couldn't resolve host name
</pre>

Perhaps it's the version?!? As I indicated, it is freelan from the wheezy-backport repository, hence
<pre>
# freelan -v
freelan 1.1 Thu 10 Oct 2013
</pre>

**Comment by s-vincent** [comment]
FreeLAN version 1.1 is no longer supported. Please update to a more recent version.
