### ISSUE TITLE
python_freelan_server: Can't use 'freelan_server network create'

### ISSUE THREAD

**Issue by aanno** [freelan-developers/freelan#92]
Using python_freelan_server from the wheezy-backport repository, I encounter the following:

The help of freelan_server says:
<pre>
# freelan_server network create -h
usage: freelan_server network create [-h] name

positional arguments:
  name        The network name.

optional arguments:
  -h, --help  show this help message and exit
</pre>

But using leads to:
<pre>
# freelan_server network create mynet
Error: __init__() takes exactly 1 argument (2 given)
</pre>

**Comment by ereOn** [comment]
The freelan server (as a Python package) was a prototype that was never fully officialy supported. It is not compatible with the latest FreeLAN release anyway. The better solution is to use the freelan binary (as you seem to do anyway from #91)

Feel free to reopen the issue if you really want to spend some time make it work (but it won't be a walk in the park).

**Comment by aanno** [comment]
Well, I didn't noticed that it is/was a prototype. A word of warning from within the server (on the main page) would avoid such hassle...

**Comment by ereOn** [comment]
@aanno Could you point me to the incorrect recommandation you followed to use the server ? This way I can fix it, and as you said, avoid the hassle for other people.

Thanks.

**Comment by aanno** [comment]
Well, perhaps it is just me. As I indicated, I'm using freelan from the wheezy-backport repository. Hence I added the repo, and used synaptic to see what is there. I felt about python_freelan_server and as I wanted to have one node in 'server-only' mode, I installed that. The documentation on the web site is a bit fuzzy about the server option...
