### ISSUE TITLE
Error deciphering data message from 

### ISSUE THREAD

**Issue by richman1000000** [freelan-developers/freelan#93]
On debian x86_64:

```
freelan[23594]: Error deciphering data message from 212.154.135.122:12000: error:00000000:lib(0):func(0):reason(0)
```

Sometimes, after this error appears freelan cannot be started properly again untill computer is rebooted.

**Comment by achedeuzot** [comment]
I got this message a lot lately with a lot of 

```
freelan[7880]: Error deciphering data message from 1.2.3.4:2121: error:00000000:lib(0):func(0):reason(0)
freelan[7880]: Session with 1.2.3.4:2121 lost (timeout).
freelan[7880]: Removed system route: eth0 - 1.2.3.4/32 => 10.1.160.114 - metric 0
freelan[7880]: Accepting PRESENTATION from 1.2.3.4:2121 for pre-shared key authentication: same ...tation.
freelan[7880]: Session established with 1.2.3.4:2121.

$ freelan --version                                                                                                          [0]
freelan 2.0.0 (<unspecified version>) Tue 15 Nov 2016
```

I'm using freelan with cross connections between all my servers: each server is connected to all the others directly through public IPs. I currently have 9 servers. Since this morning, nearly all the connections are unstable and can't stay up. Any idea what could be causing this ?

**Comment by richman1000000** [comment]
I think this is some sort of ssl library error. 
Freelan work fine several month, but what I did is setup each server configuration like this. 
ipv4_address_prefix_length=10.18.0.10/23 (address of this server)
never_contact=10.18.0.10 (again address of this server)

**Comment by richman1000000** [comment]
this error
[ERROR] Error deciphering data message from 10.1.2.3:2121: error:00000000:lib(0):func(0):reason(0)
happens when there is not enough virtual memory during  memory leakage  described  in 
https://github.com/freelan-developers/freelan/issues/74#issuecomment-307067381

But setting up swap-file to 50 Gb resolved this problem partially

**Comment by s-vincent** [comment]
@richman1000000 do you still use a freelan 2.0.0 binary ? It comes from official debian package ?

I tried some stuff recently and I cannot see any growing leaks with latest code (2.1). Can you try with master repository ?

**Comment by richman1000000** [comment]
Hi!
Ok, I can compile linux version, but I do not know how to compile windows version :( .

**Comment by richman1000000** [comment]
got error during compilation and package build.
debian 9.1 all packages up to date with main repository.

![image](https://user-images.githubusercontent.com/9943374/29104696-4e473d7e-7ce9-11e7-85fa-45af53c60903.png)

**Comment by s-vincent** [comment]
GNU/Linux Debian 9.1 uses OpenSSL 1.1.0. You can use openssl1.1.0 branch (see #113). Hopefully we will merge it to master soon.

**Comment by richman1000000** [comment]
yes, this branch successfully compiled.
Do I need to install it on all clients? Cause memory leak occurs only on central server with switch role.

**Comment by ereOn** [comment]
@richman1000000 The two versions should be compatible, but if you have the chance, it's always safer to use the same version on both sides.

**Comment by s-vincent** [comment]
@richman1000000 To build on Windows it is a little bit tricky! I have done some stuff yesterday about that so be sure to use last revision of the master repository.

First you need to install Visual Studio 2017 with C++ support and Windows 10 SDK 10.0.5063.0 (desktop edition). Normally it is proposed by the online installer of Visual Studio 2017 Community.

You will need Python 2.7, ActivePerl packages and teapot. In case you have [chocolatey](https://chocolatey.org/install) package manager installed, run the following in an adminstrator shell:
```
choco install ActivePerl python2
c:\Python27\python.exe -m pip install teapot
```

Then open a "x64 Native Tools Command Prompt for VS 2017" shell and go to the freelan repository (no need for administrator privileges), and type:

```
teapot build
nmake -f Makefile.windows build_x64
```
After some (long coffee) time, the binary will be located in `install\x64\release\bin`

If you want to generate a 32-bit version, follow the same as before except you have to use a "x86 Native Tools Command Prompt for VS 2017" shell and `nmake -f Makefile.windows build_x86`.

**Comment by richman1000000** [comment]
Hi!
I will try to compile it for windows this weekend, but I would prefer to find a way to collect debug data into file so we can perform later analysis . 

Cause as I see in log files, this error  and concomitant memory leak #74 , if it will appears,  always caused by same windows machine. 

Aug 10 07:54:52 richard freelan[4524]: Error deciphering data message from 10.17.0.125:12000: error:00000000:lib(0):func(0):reason(0)

**Comment by s-vincent** [comment]
Hi,

You can try to run the command with valgrind --leak-check=full --show-reachable=yes ./the_program --arguments (see http://valgrind.org/docs/manual/mc-manual.html#mc-manual.leaks).

**Comment by richman1000000** [comment]
Hi!
I've tried to compile it in windows but after successfully compiling, adding any certificate to file freelan exits with error
![image](https://user-images.githubusercontent.com/9943374/29648897-a6002ba0-88b2-11e7-9a6d-7192def6215c.png)

**Comment by richman1000000** [comment]
trying to compile openssl1.1.0 branch (see #113). ends up with error 
![image](https://user-images.githubusercontent.com/9943374/29648958-02f56640-88b3-11e7-8336-caae5005dd01.png)

**Comment by s-vincent** [comment]
@richman1000000 According to https://www.openssl.org/docs/faq.html, try to add the following in apps/freelan/src/main.cpp somewhere before namespace fs:

#ifdef MSV
#include <openssl/applink.c>
#endif

**Comment by leggewie** [comment]
@richman1000000 Any progress here?

**Comment by richman1000000** [comment]
In my test this error always  happens only during memory leak. #74 
I think you can close this issue, it is just consequence of root cause described in #74

**Comment by leggewie** [comment]
OK, thank you for reporting back.  Please don't hesitate to report any further issues you may find.
