### ISSUE TITLE
user requires contact information

### ISSUE THREAD

**Issue by richman1000000** [freelan-developers/freelan#94]
In  freelan log there is this record.
1) in server mode there is  error "user (ip) asked for contact information without an active registration. Denying."
during this time client cannot connect to new peers. 
Instead of denying, server must request client to registration again. Client receives this answer and instantly will re-register.

this 2 errors is related
2) in log of peer (ip1) "Received a data message from (ip2) but no session exists. Ignoring." because of that from (ip2) it looks like they connected, but VPN connection actually is not working.
peer need to return answer " no session exists" to client  (ip2), and (ip2) will send new session request .

2.1)  "Ignoring PRESENTATION from (ip1) as an active session currently exists with this host."
this is same error but in log of (ip2). peer (ip2) must  forget old session and new accept PRESENTATION from (ip1).

**Comment by ereOn** [comment]
I'm not sure to understand completely what the issue is.

The error message: "user (ip) asked for contact information without an active registration. Denying." has a simple solution: the client must properly register before issuing requests to the server. Am I missing something ?

**Comment by richman1000000** [comment]
when server is denying request in client log  this error appears. "
2015-10-01T09:10:10.383536 [DEBUG] Sending HTTP(S) request to http://(server ip)/get_contact_information/: 200
2015-10-01T09:10:10.391528 [ERROR] Failed to get contact information from the web server: Unsupported content type (freelan::web_client_error:1)."

Client do not attempt to proper register until wrong registration information will expire on the client side or client itself is restarted. Restarting client in usually unavailable. 
During this time client is unable to receive contacts of other clients which properly registered.

It happens when server is restarted.
If server will stop crashing ( #83  ) this issue will be less important.
Actually, I think this  issue is not an error, more like improvement.

**Comment by bhzhu203** [comment]
uncomment   “enabled=yes” will help
[server]
#enabled=yes

**Comment by richman1000000** [comment]
bhzhu203 I think you did not read properly or understood the issue. "in server mode" - Server is enabled on server machine.
