### ISSUE TITLE
dynamically established link is not used for data messages

### ISSUE THREAD

**Issue by richman1000000** [freelan-developers/freelan#96]
Server C with public ip and relay mode enabled  is contacted by 2 clients - A and B.
A and B dynamically contact each other.
After dynamic connection is established data still goes through server C.
Data path is A-C-B.
If I turn off server C - clients A and B will exchange session information, but no data goes through. Inside VPN they are unreachable.

clients must switch to dynamically established link after it is established and use relay server if dynamic link is lost.

**Comment by ereOn** [comment]
That is surprising. Are you in tun or tap mode ?

In tap mode, the internal virtual switch should expire entries after a while so that the proper route be taken by the next frames.

When this happens, can you try and send a broadcast message from A or B ? Something like a broadcast ping or broadcast UDP message. If the link between A & B is established, the other side should receive the message and update its internal switch-routing table.

**Comment by richman1000000** [comment]
hi!
I use tap mode. Yes, I tried to send ping pockets inside network from A to B - does not work.
If C with relay mode goes down - AB cannot reach each other

I turned off relay mode on C, and  configured clients to  dynamically contact each other - A searches for B, B searches for A. This reduced VPN connection downtime, but with relay mode on connection will more stable

PS. interesting fact.
server C have wireless internet, so it have unstable ping time from 150ms up to 1000 ms, same is true inside VPN. AB direct  peer connection have only 40 ms ping! That is awesome! That's why I like freelan.

**Comment by leggewie** [comment]
This bug is marke to block release of 2.1.

@richman1000000 Are you still experiencing this issue? What version are you using?

**Comment by richman1000000** [comment]
Hi!
I do not use this model of connection for now, but I will check it again this week.
Also you can reproduce it yourself easily.

**Comment by leggewie** [comment]
Did you have a chance to check this, @richman1000000?

**Comment by richman1000000** [comment]
Hi!
Yes, I've checked it.

In new version, compiled from master branch it worked perfectly. I think we can close this issue.

**Comment by leggewie** [comment]
Awesome!  Thank you.

Closing.
