### ISSUE TITLE
Issue installing on ubuntu 14.04

### ISSUE THREAD

**Issue by gouthamvel** [freelan-developers/freelan#99]
Followed instructions on http://www.freelan.org/download.html#debian

> root@vpn-euro:~/freelan-all# apt-get install freelan
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  freelan : Depends: libasiotap2 (>= 2.0) but it is not going to be installed
>            Depends: libfreelan2 (>= 2.0) but it is not going to be installed
>            Depends: libfscp2 (>= 2.1) but it is not going to be installed
>            Depends: libiconvplus1 but it is not going to be installed
>            Depends: libkfather1 but it is not going to be installed
>            Depends: libboost-system1.49.0 but it is not installable
>            Depends: libboost-thread1.49.0 but it is not installable
>            Depends: libboost-program-options1.49.0 but it is not installable
>            Depends: libboost-filesystem1.49.0 but it is not installable
> E: Unable to correct problems, you have held broken packages.

**Comment by ereOn** [comment]
I suspect you tried installing the 1.1 version.

The official freelan Debian package for the 2.0 version is slowly making its way through the official Debian channels. In the meanwhile, it is highly recommended to compile from source. It's really easy to do on Linux and all the instructions are provided in the repository `master` branch.
